### ISSUE TITLE
install TRACCAR on ArchLinux Raspberry b+ not working

### ISSUE THREAD

**Issue by jjrask** [traccar/traccar#1247]
hi,

i I'm all new in this .
I have managed to get the traccar server run under the root user. However I would like the deamon to run ALL the time - from startup of system
I have tried to start traccar this way 
```
./traccar install
```
but gets messaged that no pass exist for init.d and for 3 more files

**Comment by tananaev** [comment]
Is it `armhf` or `armel` system?

**Comment by jjrask** [comment]
ehhh ?? how do I see that ?

**Comment by tananaev** [comment]
Basically the problem is that Java Service Wrapper (library used to run Traccar as a service) is built for `armv7` and is not compatible with Raspbery Pi `armv6` hard floating architecture.

More details here: https://sourceforge.net/p/wrapper/mailman/message/30767505/.

You can try to build wrapper yourself for `armv6` architecture as suggested in the thread.

**Comment by lingan-se** [comment]
I run it on a rasp, armhf, but with cron-job startup at boot. Works fine.
Cron:
 	java -jar /opt/traccar/tracker-server.jar /opt/traccar/conf/<yourconfigfile.cfg>

**Comment by Devouzer** [comment]
I use perfect raspberry smooth, detail is that I want to configure the database and can not achieve achievement install h2 do not :( I'm from Peru.

**Comment by tananaev** [comment]
@Devouzer, you don't need to install H2. It's embedded in the server. You just need to give it a full path where you want to store your database file.
