### ISSUE TITLE
Database Performance with 10k + clients

### ISSUE THREAD

**Issue by cruxioneffux** [traccar/traccar#1248]
I want to know how traccar will scale under large no of devices around 10k+ each sending data 5 seconds.

I saw some code (mostly database) and from what I understand there will be a blocking call (let say using JDBC)  to database and that will take some time.

We are getting on server 10,000 request per 5 seconds i.e. 2000 request / second , and 2000 requests/ location cannot be written to a database in a second (well depends on DB and other things but we know DB's aren't so fast ).

So the database will lag behind the actual location the devices are at .Right ?
 So how do you handle this ?

**Comment by tananaev** [comment]
In the current version the insert call is synchronized, but it the new version that I'm working on at the moment it won't be, so you can have parallel calls to the database. There is no async/non-blocking APIs in Java to work with database as far as I know, so this is the best possible solution.

Properly configured database should be able to handle 2000 requests per second.

**Comment by cruxioneffux** [comment]
Yes no properly documented API's  for async DB calls are available as of now and yes this is the only choice.

And thus the problem still remains.

2000 request/ inserts /updates per second ?
I think updates will search for whole table and thus much time and thus will not allow 2000 updates in a second !

The query to insert a record will take some time on DB ( some milliseconds ? I am using MS SQL Server and it takes 1ms and 6ms for a typical insert/update ).
Thus only 1000 inserts in a second(just 166 updates) and thus 1000 inserts(1834 updates) lag and this will keep on adding each second as the requests / locations come in(2000 each sec) and thus won't the database lag(especially for updates) ?

Parallel calls using n different threads  ? Will it reduce the problem by factor of n . So if n = 10 then there will now be 200 request with each and thus get completed in 200 ms ?

**Comment by tananaev** [comment]
If an update goes through whole table, it means something is not right. Most likely table doesn't have required indexes.

If it's a simple insert and update, MS SQL server can handle much more than 1000 requests per second. Threading should solve the issue of delays caused by synchronous communication between Traccar and database.

**Comment by wahisoufiane** [comment]
We have a MySQL DB, and about 1K devices, sending a record each 2 to 10 seconds, but we are getting a delay between the generated record and insert them to the DB (about 5 to 15min).

Before we attempt 1K devices, we had just 500 devices or less, and everything went right (about 0 to 30 seconds between generated record and insert).

When I profile the record excecution time, I found that it took in average 2 second, instead of 100ms or less in the begining.

My record table is over 100M records, I wonder if the problem is came from the record table number of rows, or the traffic of the records who wan'ts to be treated, or the limit of MySQL??

**Comment by tananaev** [comment]
Possible issues:

1. Hardware
2. Old version of MySQL
3. Not optimized MySQL

@wahisoufiane, I would recommend opening a new issue if you want to discuss it further.
