### ISSUE TITLE
Question : What is power column value if device on or off. I always get null value in power column.

### ISSUE THREAD

**Issue by myexpertiseforyou** [traccar/traccar#1319]
@kero99 @demianalonso @abc1212 @prsolucoes @arekinath 
Hello forks,
I have query regarding power value in position table. Can you pleas in which case power value update.

**Comment by tananaev** [comment]
GT06 can send a few different types of messages. Usually the problem is that GPS data is sent in one message and status (which includes power) is sent in another. Traccar currently doesn't support messages without GPS info, so status messages are ignored by server.

PS Please don't spam everywhere with your question. One place is enough.

**Comment by surendrakumar1992** [comment]
@tananaev  really sorry for that.
Can you please describe me 'other' column.
<info>
<protocol>gt06</protocol>
<satellites>9</satellites>
<acc>false</acc>
<mcc>404</mcc>
<mnc>70</mnc>
<lac>51</lac>
<cell>14090240</cell>
<index>1119</index>
</info>
Really sorry Man. I am waiting your reply :(

**Comment by al3x1s** [comment]
It's an additional information obtained from GPS device like battery level, protocol, alarm, etc.
it can be different depending on what information can provide each GPS
