### ISSUE TITLE
About device connection status

### ISSUE THREAD

**Issue by gpsim** [traccar/traccar#1540]
See you increase the function of the device connection state, but did not configure the XML to the database sql,
I try to configure SQL to XML, the state has changed, but because of the lastUpdate type lastUpdate will follow the change

**Comment by tananaev** [comment]
Sorry, but I don't understand the problem.

**Comment by gpsim** [comment]
Sorry, my English is not very good, I mean, after adding equipment status information,device's lastUpdate always keep the change, and not to increase the record will change.

**Comment by tananaev** [comment]
It's still not clear. Does or does not the `lastUpdate` change?

**Comment by gpsim** [comment]
The 'lastUpdate' field in the device is always changing.

**Comment by tananaev** [comment]
It's changing every time server gets any message from device.

**Comment by jamejo** [comment]
One more thing to consider is the 'lastUpdate' Default should not be set to 'Current TimeStamp' if it is, then the problem is that even if any other query is run on the device table the TimeStamp will be updated.

Cuz 3.1 and 3.2 default setup still configures the lastUpdate column to be 'On Change Current TimeStamp'

**Comment by tananaev** [comment]
@jamejo, I still don't understand where that default came from. I guess I need to try fresh install and see if it happens again.
