### ISSUE TITLE
Timeline [New feature request]

### ISSUE THREAD

**Issue by sosoxuc** [traccar/traccar#1546]
Would be great to have timeline report

You chose device and timeline is shown. X - time, Y - speed. As you slide through time device location is shown on the map at that moment.

**Comment by tananaev** [comment]
It should be a nice addition to history re-play functionality.

**Comment by nelim** [comment]
Is there an easy way to calculate traveled distance (approximately between points of course) on specific report? Maybe something already in your plans also :)

**Comment by tananaev** [comment]
You can add following line to the config to calculate distance:
<pre>&lt;entry key='distance.enable'&gt;true&lt;/entry&gt;</pre>

**Comment by nelim** [comment]
Is it reported by device, or calculated from the server?
I enabled it and made two tracks with both incar tk103 and traccar android client, both stay Distance: 0 km on device status. tk103 has also odometer: 0km which is normal, because it is not connected to my car ECU (i'm not sure it has that option also). 

ps. Sorry for interrupting another issue, maybe i need to open another one (it is not actually issue), or contact you somewhere else? Thanks in advance.

**Comment by tananaev** [comment]
Does it show in state panel?

**Comment by nelim** [comment]
No, both stays on 0, on last point and all other points from today
![screenshot - 271115 - 11 12 01](https://cloud.githubusercontent.com/assets/3601587/11437603/bfc19e6c-94f7-11e5-8040-c49e13fd427a.png)
![screenshot - 271115 - 11 12 16](https://cloud.githubusercontent.com/assets/3601587/11437610/c7403554-94f7-11e5-8fb2-3c75c0b6fa18.png)

**Comment by tananaev** [comment]
Just fixed it in cde6259e36d2ec312b5d67a5e2a75bfff41a24c3. You need to update web interface.

**Comment by nelim** [comment]
Thanks, everything is fine now, it shows 10+km with new app.min.js :) :+1:
