### ISSUE TITLE
Complete solution of GPS Tracker

### ISSUE THREAD

**Issue by anandraj204** [traccar/traccar#1647]
Hi,

I am new in GPS Tracker, i dont know how can i start.
I was intall traccar in my system.

Initially I have some doubts, I need to know 

1.How to get login in OpenGPS ?
2.How many GPS able to connect with Traccar and OpenGPS ?
3.How many request send GPS in a Second and What about the server load ?
4.Which GPS kit is better in Traccar ?

**Comment by tananaev** [comment]
Why are you asking about OpenGTS? Have you integrated Traccar with OpenGTS system?

**Comment by anandraj204** [comment]
Yes, I wanna integrate Traccar with OpenGTS system.

**Comment by tananaev** [comment]
When you integrate Traccar with OpenGTS, Traccar just writes data directly into OpenGTS database. So, you need to use standard OpenGTS tools to work with the system. Traccar interface won't be available.

As for other questions:

2. Traccar has been tested with 30k devices and more
3. Traccar can handle 8k messages per second and possibly more with proper configuration
4. I can't recommend anything because I don't have much experience with actual hardware

**Comment by anandraj204** [comment]
Thanks, these answers really helpful to proceed next step of my project.

**Comment by SebastEnn** [comment]
Questions answered. Issue can be closed.
