### ISSUE TITLE
Real time tracking

### ISSUE THREAD

**Issue by Pashayan** [traccar/traccar#1657]
Dear Anton, can i see real time tracking of gps without refreshing the web page every time?

**Comment by tananaev** [comment]
Yes, you can. Traccar uses WebSockets for live data update.

**Comment by kzwai** [comment]
how can I do that

**Comment by tananaev** [comment]
Do you mean programmatically? Look at what official Traccar web app does.

**Comment by kzwai** [comment]
Dear Tananaev
thankx a lot for this program ,,Really you let me dive deeply inside it ,I am not programmer I am just communication and control Engineer, now I am installing Traccar 4.3 in server and I am play with it ,,and I am registering my smart phone with Traccar App, its really good I am adjusting the frequency at 1 ,,its real time movement and the pointer is walking in my screen ,,but when I register my bofan pt502 its ok I can see it in server with green online ,,,the problem is the program take lot of time to update position ,,some times takes 4 hours' ,,,does any special configuration in Traccar.xml in configuration file ,,another problem I can see websocket error ,,,please advice
Regards........

**Comment by tananaev** [comment]
For questions you should use forum. Also, I would recommend to write with proper punctuation if you want to receive any response.
