### ISSUE TITLE
filter.limit

### ISSUE THREAD

**Issue by mm108** [traccar/traccar#1911]
I have the following filter enabled with a interval of at least 29 seconds. 

```
    <entry key='filter.enable'>true</entry>
    <entry key='filter.limit'>29</entry>
    <entry key='filter.invalid'>true</entry>
    <entry key='filter.duplicate'>true</entry>
```

So I assume that there will be a gap of minimum 29 seconds but I see these records, the gap is only 4 seconds. Am I missing anything?

```
uniqueid        dateisoutc                                                  address     speedkph    latitude    longitude
359710043724460 4/27/2016 22:42:04 GMT+0800 (Malay Peninsula Standard Time) {address}   0           1.311298    103.630237
359710043724460 4/27/2016 22:42:11 GMT+0800 (Malay Peninsula Standard Time) {address}   6.700000    1.311228    103.630248
```

Thanks,
M.M

**Comment by tananaev** [comment]
The limit works the opposite way. It's the maximum limit between messages, not minimum.

**Comment by m-menon** [comment]
oh okay thanks :)

**Comment by m-menon** [comment]
can I know the reason behind that? I mean I thought that it would be more appropriate to have it the other way around - cos you may not want trackers to continuously bombard your server with position data every few seconds as too many points would be a waste of resources and space too - not to mention they appeat awful on the map if not spaced correctly. Thanks

**Comment by tananaev** [comment]
The reason for this parameter is to get updates in case object is not moving for a long period of time. For example, you left your car on a car park for a few days, so you don't want to get updates every 1 minute because it doesn't move, but you still want to get updates let's say every hour or couple of hours to make sure everything is fine.

If you don't want too many messages, you either reduce the report period on the device or set a distance filtering. I don't see why you would need server-side time filtering.

**Comment by m-menon** [comment]
Thanks a lot for the explanation. Yes, that definitely makes sense. The only reason I was thinking about the minimum interval was because the trackers are configured by other users and many times they use unduly high update rate (like once every 3-5 sec etc) and so it seems like unnecessary use of the resources in terms of computing, disk space etc. Moreover too many points on the map don't look elegant too. Thanks

**Comment by SebastEnn** [comment]
Question answered. Issue can be closed.
