### ISSUE TITLE
Device motion status is not updating

### ISSUE THREAD

**Issue by mrameezraja** [traccar/traccar#2142]
I am using sql server database and custom frontend, here is the query for `database.updateDeviceStatus` 
`UPDATE GPS_DEVICES SET STATUS = :status, MOTION_STATUS = :motion WHERE imei = :uniqueId`
Status is updating successfully but motion status is not updating in any case. Am i missing something?

-Thanks

**Comment by Abyss777** [comment]
Hello
First of all, are you using 3.6 version?
Motion status is an integral part of events subsystem. Have you enabled it? 
````
<entry key='event.enable'>true</entry>
<entry key='event.motionHandler'>true</entry>
````
As I can see you are using custom database scheme, you have to implement other things related to events and notifications subsystem.

and still there can be some issues, because it is not tested with custom schemes.

Actually, there are plans to remove `motion` from model and database. I would recommend you not rely on it in your frontend.

**Comment by mrameezraja** [comment]
enabling event did the trick. Thanks @Abyss777
