### ISSUE TITLE
SQL Server schema for traccar v3.7

### ISSUE THREAD

**Issue by jbenitezlavado** [traccar/traccar#2379]
Hi someone can share me the SQL Server schema for traccar v3.7.

Thanks.

**Comment by tananaev** [comment]
It's constructed changelog files:

https://github.com/tananaev/traccar/tree/master/schema

**Comment by akmal1999** [comment]
Many thanks!
Would you also have the MSSQL connection strings?
I dont know if this is working:

<entry key=’database.driverFile’>C:\ANX\sqljdbc42.jar</entry> "Is this an ok way to put the sqljdbc, I extracted this, it has 3 folders which makes me confused as how to put it correctly"
<entry key=’database.driver’>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>
<entry key=’database.dataSource’>com.microsoft.sqlserver.jdbc.SQLServerDataSource</entry>
<entry key=’database.url’>jdbc:sqlserver://MyServer;user=sa;password=MyPassWord</entry>
<entry key=’database.user’>sa</entry>
<entry key=’database.password’>MyPassWord</entry>

**Comment by akmal1999** [comment]
<entry key=’database.driverFile’>C:\ANX\sqljdbc42.jar</entry>
<entry key=’database.driver’>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>
<entry key=’database.dataSource’>com.microsoft.sqlserver.jdbc.SQLServerDataSource</entry>
<entry key=’database.url’>jdbc:sqlserver://MyServer;user=sa;password=MyPassWord</entry>
<entry key=’database.user’>sa</entry>
<entry key=’database.password’>MyPassWord</entry>

**Comment by tananaev** [comment]
It looks like you haven't specified database name. Check this page:

https://www.traccar.org/ms-sql/

**Comment by akmal1999** [comment]
Many thanks, I am sorry for being so specific about this. does below mean we have to put it like.
<entry key='database.driver'>servername.**jdbc.SQLServerDrive**r</entry>
what does the **.jdbc.sqlserverdriver** refer to? is this the odbcconnection we made in odbc connection in the server? could you put a fake example.

derived from below referring to above.
<entry key='database.driver'>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>

**Comment by akmal1999** [comment]
And also: what is the difference between the two users:

<entry key='database.url'>jdbc:sqlserver://[serverName][\instanceName];user=[userName];password=[password];databaseName=[database];</entry>
<entry key='database.user'>[userName]</entry>
<entry key='database.password'>[password]</entry>

are we usually use a sysadmin user that has access to the database instance and we use usually the sa or we call it the db owner to the database? can both be a sql user?

**Comment by akmal1999** [comment]
Hi,
Adding everything like below for sql db. I am getting the below error.

<entry key='database.driverFile'>C:\Program Files\Traccar\lib\sqljdbc42.jar</entry>
<entry key='database.driver'>OL2UKHH.jdbc.SQLServerDriver</entry>
<entry key='database.url'>jdbc:sqlserver://OL2UKHH\mygps;user=sa;password=sapassword;databaseName=mygps;</entry>
<entry key='database.user'>sa</entry>
<entry key='database.password'>sapassword</entry>


STATUS | wrapper  | 2016/10/15 08:08:58 | --> Wrapper Started as Service
STATUS | wrapper  | 2016/10/15 08:08:58 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/10/15 08:08:58 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/10/15 08:08:58 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/10/15 08:08:58 | 
STATUS | wrapper  | 2016/10/15 08:08:58 | Launching a JVM...
INFO   | jvm 1    | 2016/10/15 08:08:59 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 22; columnNumber: 6; The content of elements must consist of well-formed character data or markup.
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at sun.util.xml.PlatformXmlPropertiesProvider.load(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at java.util.Properties$XmlSupport.load(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at java.util.Properties.loadFromXML(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at org.traccar.Config.load(Config.java:29)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:141)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: Caused by: org.xml.sax.SAXParseException; lineNumber: 22; columnNumber: 6; The content of elements must consist of well-formed character data or markup.
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.startOfMarkup(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(Unknown Source)
INFO   | jvm 1    | 2016/10/15 08:09:00 | WrapperSimpleApp Error: 	... 12 more
STATUS | wrapper  | 2016/10/15 08:09:02 | <-- Wrapper Stopped

**Comment by tananaev** [comment]
The error means that your XML file is invalid:
```
lineNumber: 22; columnNumber: 6; The content of elements must consist of well-formed character data or markup.
```

Some more information about Microsoft JDBC driver:

https://msdn.microsoft.com/en-us/library/ms378428(v=sql.110).aspx

**Comment by akmal1999** [comment]
Found the issue was with a commenting out.. however , now I am getting following issue. I will look into the link you sent me.

TATUS | wrapper  | 2016/10/15 13:19:14 | Launching a JVM...
INFO   | jvm 1    | 2016/10/15 13:19:14 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: java.lang.ClassNotFoundException: OL2UKHH.jdbc.SQLServerDriver
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at java.net.URLClassLoader.findClass(Unknown Source)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at java.lang.ClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at java.lang.ClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at java.lang.Class.forName0(Native Method)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at java.lang.Class.forName(Unknown Source)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.initDatabase(DataManager.java:94)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.<init>(DataManager.java:66)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:150)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/10/15 13:19:15 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Unknown Source)
STATUS | wrapper  | 2016/10/15 13:19:18 | <-- Wrapper Stopped

**Comment by tananaev** [comment]
Now database configuration is incorrect. What is "OL2UKHH.jdbc.SQLServerDriver"? It's definitely incorrect. Where did you get it from?

**Comment by tananaev** [comment]
Driver class name is `com.microsoft.sqlserver.jdbc.SQLServerDriver`. Why would you modify it?

**Comment by akmal1999** [comment]
Thanks, that is fixed and my bad I have amended that for no reason. Service started however, I see some errors.

first of all service runs and gives "503 - Service Unavailable"

Here is the log 

**INFO   | jvm 1    | 2016/10/15 22:10:51 | [Thread-15] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@36ca05b6{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2016/10/15 22:10:51 | [Thread-15] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.w.WebAppContext@533b7613{/,file:/C:/Windows/Temp/jetty-0.0.0.0-8082-traccar-web.war-_-any-2862334566163662806.dir/webapp/,UNAVAILABLE}{c:\Program Files\Traccar\traccar-web.war}
INFO   | jvm 1    | 2016/10/15 22:10:53 | [Thread-15] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@37dae84b{/api,null,UNAVAILABLE}
STATUS | wrapper  | 2016/10/15 22:10:54 | <-- Wrapper Stopped
STATUS | wrapper  | 2016/10/15 22:11:50 | --> Wrapper Started as Service**
STATUS | wrapper  | 2016/10/15 22:11:51 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/10/15 22:11:51 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/10/15 22:11:51 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/10/15 22:11:51 | 
STATUS | wrapper  | 2016/10/15 22:11:51 | Launching a JVM...
INFO   | jvm 1    | 2016/10/15 22:11:51 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/10/15 22:11:53 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2016/10/15 22:11:54 | [WrapperSimpleAppMain] INFO **com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Driver does not support get/set network timeout for connections. (This operation is not supported.)**
INFO   | jvm 1    | 2016/10/15 22:11:55 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @3369ms
INFO   | jvm 1    | 2016/10/15 22:11:56 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.19.v20160908
INFO   | jvm 1    | 2016/10/15 22:11:58 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@7727d654{/api,null,AVAILABLE}
INFO   | jvm 1    | 2016/10/15 22:12:14 | [WrapperSimpleAppMain] INFO **org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet**
**INFO   | jvm 1    | 2016/10/15 22:12:24 | [WrapperSimpleAppMain] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@2d20a41{/,file:/C:/Windows/Temp/jetty-0.0.0.0-8082-traccar-web.war-_-any-4442421638176066230.dir/webapp/,STARTING}{c:\Program Files\Traccar\traccar-web.war}**
**INFO   | jvm 1    | 2016/10/15 22:12:24 | java.lang.RuntimeException: Unable to perform DB migrations
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.traccar.web.server.model.DataServiceImpl.init(DataServiceImpl.java:77)**
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.init(RemoteServiceServlet.java:168)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:117)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:102)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:172)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:138)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:852)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.server.Server.start(Server.java:387)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.traccar.web.WebServer.start(WebServer.java:179)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.traccar.Main.main(Main.java:40)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/10/15 22:12:24 | Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not execute statement
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1771)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:87)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.traccar.web.server.model.DBMigrations$SetDefaultExpiredFlagForEvents.migrate(DBMigrations.java:406)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.traccar.web.server.model.DBMigrations.migrate(DBMigrations.java:72)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.traccar.web.server.model.DataServiceImpl.init(DataServiceImpl.java:75)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	... 32 more
INFO   | jvm 1    | 2016/10/15 22:12:24 | Caused by: org.hibernate.exception.SQLGrammarException: could not execute statement
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:123)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:109)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:78)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:445)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:379)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1286)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:118)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.jpa.internal.QueryImpl.internalExecuteUpdate(QueryImpl.java:371)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:78)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	... 35 more
INFO   | jvm 1    | 2016/10/15 22:12:24 | Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'events'.
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2444)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:328)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
INFO   | jvm 1    | 2016/10/15 22:12:24 | 	... 43 more
INFO   | jvm 1    | 2016/10/15 22:12:24 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@371d37a5{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2016/10/15 22:12:24 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - Started @33266ms

**Comment by tananaev** [comment]
Now you are not using official version of Traccar.

**Comment by akmal1999** [comment]
I am using the 3.7 is that not official?

**Comment by tananaev** [comment]
It is, but it seems like you installed non-official UI on top of it.

**Comment by akmal1999** [comment]
I have not done that, used following link to and change of traccar.xml that you have advised for installation and nothing else....

http://traccar.litvak.su/installation.html

is this not official?

In any case, I will appreciate your help as you have supported others for the same installation..

**Comment by tananaev** [comment]
No, it's not. Here is the official Traccar website:

https://www.traccar.org/

**Comment by akmal1999** [comment]
ho ok. I understood now. thanks. 

If you know what the problem is with the log I have sent I would appreciate your feedback.. I see you have helped alot of others with this installation.

**Comment by tananaev** [comment]
I can help with official Traccar version. I would recommend to use the official one.

If you decide to use third party mod, you should contact the author of the mod for help.

**Comment by akmal1999** [comment]
Ok Thanks.
