### ISSUE TITLE
Can traccar support my GPS tracker TOPFLYTECH T8803 ?

### ISSUE THREAD

**Issue by guruhsdr** [traccar/traccar#282]
I have bought GPS tracker TOPFLYTECH T8803 and try used traccar. But In the log i saw this:

```
2013-05-31 15:22:07 org.traccar.BasePipelineFactory$StandardLoggingHandler.log FINE: [5011 <- 120.168.0.118] - (HEX: 283838303331363839303039343931304250303058473030623630303030303030304c3030303734623534533030303030303030523043304630303134303030313030663031333035333131353232303541303730362e313339355331313032342e30393635453030302e303235312e323529)
2013-05-31 15:22:30 org.traccar.BasePipelineFactory$StandardLoggingHandler.log FINE: [5011 <- 120.168.0.118] - (HEX: 283838303331363839303039343931304252303058473030623730303030303030304c3030303734623534533030303030303030523043304630303134303030313030663031333035333131353232303641303730362e313339355331313032342e30393635453030302e303235312e323529)
2013-05-31 15:27:09 org.traccar.BasePipelineFactory$StandardLoggingHandler.log FINE: [5011 <- 120.168.0.118] - (HEX: 283838303331363839303039343931304252303058473030623830303030303030304c3030303734623534533030303030303030523043304630303134303030313030663031333035333131353237303641303730362e313339355331313032342e30393635453030302e303235312e323529)
2013-05-31 15:32:05 org.traccar.TrackerEventHandler.channelDisconnected INFO: Closing connection by disconnect
```

If not support, could you help me to implement my tracker protocol in the traccar?
and give me the source code how to save the data.
I'm very need it for my graduate

Thanks a lot!

**Comment by maroun5** [comment]
Hi Can any one send me protocol documentation of topflytech_t8803.
Thanks for advance !!

**Comment by tananaev** [comment]
You can find documentation here - https://www.traccar.org/protocols/.

**Comment by digitaltrackit** [comment]
We have the topflytech model 8806 and 8803  protocol. We created socket programming where we create listeners and we are able to receive login data from tracker in  hex 23230115080357367031064944150208625060      but this one is only login data there is not langitude and longitude on this data we check protocol  server haven't I reply to login data to tracker . Can u pls explain how to do handshaking between tracker and server.

**Comment by tananaev** [comment]
You need to send a response. See the decoder:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/T800xProtocolDecoder.java

**Comment by abnan0001** [comment]
Hello All

we are getting the login data but after getting we need to send responce to device with a format that device can verify server and then send actual gps data to server.
we are not able to send login data to that device so that's why device not send us gps data.
Login Data we are getting is like :- 2323101501f357367031649441529625060.
We are not getting further process what to do to get Device gps data to our server.
below is the code :+1:
package com.trackit;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class ServerListener {

public static void main(String[] args) {
    new ServerListener().startServer();
}

public void startServer() {
    final ExecutorService clientProcessingPool = Executors.newFixedThreadPool(03);

    Runnable serverTask = new Runnable() {
        @SuppressWarnings("resource")
        @Override
        public void run() {
            try {
                ServerSocket serverSocket = new ServerSocket(5094);
                System.out.println("Waiting for clients to connect...");
                while (true) {
                    Socket clientSocket = serverSocket.accept();
                    clientProcessingPool.submit(new ClientTask(clientSocket));
                }
            } catch (IOException e) {
                System.err.println("Unable to process client request");
                e.printStackTrace();
            }
        }
    };
    Thread serverThread = new Thread(serverTask);
    serverThread.start();
}

private class ClientTask implements Runnable {
    private final Socket clientSocket;

    private ClientTask(Socket clientSocket) {
        this.clientSocket = clientSocket;
    }

    @Override
    public void run() {
        System.out.println("Got a client !");
        try {
            BufferedReader reader = new BufferedReader( new InputStreamReader(clientSocket.getInputStream()));
            String clientData = "";

            clientData = reader.readLine();

            String hex_value = asciiToHex(clientData);

            System.out.println("Hex Value :-"+hex_value);


        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private String asciiToHex(String clientData) {

        char[] chars = clientData.toCharArray();
        StringBuffer hex = new StringBuffer();
        for (int i = 0; i < chars.length; i++)
        {
            hex.append(Integer.toHexString((int)chars[i]));
        }
        return hex.toString();
    }
 }

**Comment by sameer2020** [comment]
Hello @digitaltrackit 
Is the link https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/T800xProtocolDecoder.java suggested by @tananaev resolved your handshaking issue.

As we are also facing same issue.

Thank you.

**Comment by touy** [comment]
Hi 
I have tried to convert code to python , the problem is I could not pass the login , I response to the tracker but it still sending login data , I am sure if the problem is my code , I am confusing what the thing is going one here . or I misunderstood something ? 
here is some code 

import socket
import string,sys
import thread
import struct
from datetime import datetime
#from  protocol_handler import  Protocol_Handler
import urllib2
import logging
import time 
import sys
import binascii
Port=6661
_null_trans = string.maketrans("", "")
def start_server(argv):
    #url=argv[0]
    try:
        Port=int(argv[0])
    except ValueError:
        print "Try again both value must be given!"
        return
    log_file=time.strftime("%Y-%m-%d.log")
    logging.basicConfig(filename=log_file, level=logging.INFO)
    sock=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
    sock.bind(('0.0.0.0',Port))
    sock.listen(5)
    print 'started on %s' % str(Port)
    while (True):
        newsock,address=sock.accept()
        thread.start_new_thread(handler, (newsock, address))
def handler(clientsocket, clientaddr):
    data = clientsocket.recv(1024)
    print data
    d=binascii.b2a_hex(data)
    #binascii.hexlify(data)
    print d
    print binascii.a2b_hex(d)
    myb=bytearray()
    s="232301000F00010880316890233088".decode("hex")
    #myb.append(s)
    myb=bytearray(s)
    sent=clientsocket.send(myb)
    print "sent"+str(sent)
    while(sent==0):
        print "send again"
        time.sleep(1)
        sent =clientsocket.send(myb)
        if(sent==0):
            print "socket broken"
    #binascii.a2b_hex(hexstr)
    #binascii.unhexlify(hexstr)
    close_connection(clientsocket,clientaddr)

def close_connection(sock,clientaddr):
    print "close connection to ip %s" % str(clientaddr)
    sock.shutdown(socket.SHUT_WR)
    sock.close()
def istext(s):
    if "\0" in s:
        return "it contains binary"
    if not s:  # Empty files are considered text"
        return "empty string"
    
    # Get the non-text characters (maps a character to itself then
    # use the 'remove' option to get rid of the text characters.)
    t = s.translate(_null_trans, s)

    # If more than 30% non-text characters, then
    # this is considered a binary file
    threshold=0.3
    if float(len(t)) > threshold*float(len(s)):
        return str((float(len(t)/float(len(s)))*100))+" is binary"
    return str((float(len(t)/float(len(s)))*100))+" is text"
if __name__=='__main__':
    start_server(sys.argv[1:])

**Comment by tananaev** [comment]
@touy, please create a new thread if you want to ask something.
