### ISSUE TITLE
sugestion speedlimit

### ISSUE THREAD

**Issue by andsdoug** [traccar/traccar#2854]
Hello

I think it’s not easy to configure speed limit for device in traccar.
end-users need somethink more intuitive. Maybe add new speed text box into Device panel.

**Comment by tananaev** [comment]
I agree that it would be nice to have an easier way to configure attributes. Maybe some combo-boxes with possible options.

**Comment by djbo1982** [comment]
Hello @tananaev and @andsdoug 

I agree with that, because, for now, i don´t know where is the atribute config of the platform, or what option i have with my devices... i test many other paid platform for many times, and in all we have a easy way to config the speed limit

Inclusive, old friend of you @tananaev with one UI for traccar have that option in a simple way.

Maybe for the next version we can have that option and another...

Have a good day 

PS. When we can have the new version? im crazy for test the 3.10 version

**Comment by tananaev** [comment]
Version 3.10 should be out in a couple of weeks.
