### ISSUE TITLE
Route and the distance on the map on few devices are not right

### ISSUE THREAD

**Issue by aryabiz** [traccar/traccar#2871]
Hello,
I am using my own server, Traccar version 3.9,
Device - Protocol GT06 (Concox GT06N)
Problem - Invalid route plotting and wrong distance calculation.  
![traccar_error](https://cloud.githubusercontent.com/assets/17250374/22616791/7d41d8b0-eada-11e6-8ccc-239b247bd62c.png)

My other device with same protocol are working fine, But GT06N is causing problem

Please let me know what to do.

**Comment by tananaev** [comment]
Well, I guess your device reports incorrect data. You have to find out what's wrong and possibly report it to the device vendor.

**Comment by gustavofcalmeida** [comment]
I got something similar with Traccar Client Android. The positions go in the correct sequence and suddenly the next point goes back to a very early position, and then the next gets back again to the correct sequence. Interesting thing is that the wrong point doesn't appear in a random position, but in a place you previously was. Like in @aryabiz picture, the points are always returning to that central point in the south.

**Comment by tananaev** [comment]
Possibly there is some time issue.

**Comment by gvascon1** [comment]
I had same problem.. see on picture attached that route should keep on point A, however jumped for point B (that I had stayed for a long time) and later returned for normal route. So, I don't think that's related with GPS device due coincidence to plot in a point that I had stayed for long time stopped (I guess).
![capture](https://cloud.githubusercontent.com/assets/25600062/22675160/c622f7c8-ecc2-11e6-8bcb-4cb86726d26e.PNG)

**Comment by tananaev** [comment]
Guys, instead of sending screenshots, you should go through each point one by one and see if the time matches the location. Pictured won't help to solve the problem.

**Comment by papz77** [comment]
The problem is the GPS coordinates. The point invalid have no GPS Lat, Lon but LAC and CID of cellid. You must to decode this to have valid coordinates or delete this records from database. You can search this by this query:

select * from events inner join positions on events.position_id=positions.id where positions.time>'2017-01-31 00:00:00' and positions.time<'2017-01-31 29:59:59' and positions.device_id=77 and other like '%lac%' limit 1;

this work for date 2017 01 31 and device id 77 for example, and search the last event you must delete to delete after the relative position records

1 search in events table by this query the last events to delete
2 delete from events where id=ID NUMBER found
3 repeat this to delete all events 
4 delete * from position where id=DEVICE ID and other like '%lac%'
