### ISSUE TITLE
New feature for traccar manager

### ISSUE THREAD

**Issue by aecsalome** [traccar/traccar#3164]
Hi Anton,

I'd like to propose (if is not a strong efforts) an improvement in notifications of"Trace Manager" app : it would me nice if the notifications appear integrated on the operating system screen (android and IOS), 
[similar to what happens today when we receive Gmail, SMS, etc. notification.]

This type of notification and is very useful, make sense?

**Comment by tananaev** [comment]
I'm assuming that you are talking about push notifications. It's not that easy to implement.

**Comment by Turbovix** [comment]
It may be easier to implement this feature by using the MQTT protocol discussed here: http://dalelane.co.uk/blog/?p=938

**Comment by tananaev** [comment]
@Turbovix, I don't really understand how MQTT would allow you to connect to Google and Apple push notifications infrastructure. Can you please explain.

**Comment by aecsalome** [comment]
Anton and Turbovix, thank you for feedback, I appreciate that!

@Anton, If is not that easy to implement the  push notifications, is it not a problem (was only a suggestion).
So, for me will be use to have a way to change the sound (choice my on sound tone) and volume of notification, because a single beep is hard to listen, second some feedbacks that I received.

Maybe it is already exist, and if yes, I do not found. I only am able to change the color by css.

Best regards and excelent work that traccar represents.

Alex

**Comment by aecsalome** [comment]
Complementing my previous message: @VittorJ  helped me (thanks) to workaround this question by replacing the beep.wav file. This helps, even though I can not control the volume.

Thanks @Aton for the great work with the Traccar solution

**Comment by Turbovix** [comment]
@tananaev, I do not know how to do it, although the few sensors that I have work well with ESP8266, I get all the notifications in an application on my Android. I shared because I found the MQTT protocol approach to Android interesting.
I believe that for you who are a professional and advanced developer should be only a matter of time to implement it.

**Comment by tananaev** [comment]
@aecsalome, please use correct username when you write @. By using "anton" or "Aton" you send email notification to some random people who registered account under those names and most likely never heard about Traccar and have no idea why you are referring to them.

@Turbovix, I don't think MQTT has anything to do with proper push notifications.

**Comment by deednseed** [comment]
@tananaev , Thanks Anton for the great work. I am trying to implement push notifications using FCM in manager app. Everything seems fine so far and I'm able to get push notifications on Android. However i have a problem in identifying the user to whom the notification should be sent. Since i need to maintain a mapping of username/email and deviceUniqueId. Is it possible to include additional information   (username or email of the associated user) in the forwarded event of a device? It will make life quite simple and i need not to maintain a mapping of deviceIDs and username at some other database (FCM realtime db, etc).

**Comment by tananaev** [comment]
It's not possible because single forwarded event can belong to multiple users.

**Comment by deednseed** [comment]
Oh ya..got it.. anyway, as of now I am creating topics for each registered device in FCM and subscribing each associated user with that topic, hence the notification for a device is being pushed to all associated users. But this (topic) is not the recommended way. Let me think a better workaround, will keep you updated. Thanks again for your contributions.

**Comment by atiqsamtia** [comment]
Hey, I have implemented the FCM with single tokens and tested with multiple users check out my pull request here https://github.com/traccar/traccar/pull/4002

**Comment by tananaev** [comment]
We already have push notifications support.
