### ISSUE TITLE
Suggestions for improvements

### ISSUE THREAD

**Issue by smsoousa** [traccar/traccar#3222]
Hello Anton.
I have some possible improvements and / or implementations to be studied and if possible implemented to the tracing project.

1. E-mail, sms, speed, and maintenance settings, among others, that are configured manually in the system configuration file, could have their own configuration field within the system, in a visible way. It would make the setup process easier and more accessible for less experienced users.

2. Protocols with "partial" implementations should have their functionality, at least the main one that is blocking and unlocking already implemented, because there are many crawler models that are said to be compatible with the system but do not yet have a blocking command. This becomes critical to a tracking system. One of them would be the MXT140 protocol.

3. I also thought of a "show on the map" button that could be placed next to the "devices" panel. So that by clicking on the device and clicking the show button on the map, the zoom is enlarged to its limit, to show the vehicle with an acceptable location view, and not to manually zoom whenever you need to see the location of a device .

4. You could also implement a new status or status to find out if the vehicle is on or off and the engine is locked or unlocked. I know that for some cases this information already appears in the state of the device, but I thought of making this information even more visible, being able to create a small icon with coloration, green to unlocked and red if blocked for example. And to ignite a key icon, green to on and red to off, it would be great to see this functionality in the system.

At first this is, I have other ideas yet to set out, but I will formalize them better before sharing with you. I hope my ideas can somehow contribute to the project's growth. Thanks in advance!

**Comment by tananaev** [comment]
1. We are working on improving it, but those are still recommended to be configured in the config file. It's done once by admin, so I think it's appropriate.

2. You should assume that only basic functionality is support, which is receiving GPS location info. There are almost no protocols that are "fully" supported because some features might not be available in Traccar or vendor changed protocol etc.

3. This has already been suggested before.

4. Not all devices support this, so I don't think making it more visible makes much sense. Traccar is not only for vehicle tracking.

Also, in future I would recommend that you search for your suggestions first. If something similar already exists, you should comment on the existing thread.

Also, you should definitely have separate thread for every suggestion so it can be discussed separately. Otherwise it becomes a mess.

**Comment by tananaev** [comment]
Please split feature requests into separate tickets.
