### ISSUE TITLE
GT06 protocol ignition decode

### ISSUE THREAD

**Issue by socstur** [traccar/traccar#3564]
Hi Guys,
             I'm showing below a gt06 0x22 packet that is supposed to include ignition state according to documentation but Traccar is  decoding ignition as "YES". Documentation below shows "00" is low state for ignition and the packet is reporting "00" as shown below. The install is configured to copy ignition attribute but this packet contains ignition so it should not be copying from older packet.

![image](https://user-images.githubusercontent.com/15850216/31143841-4e3b9484-a844-11e7-998e-886b49c063b7.png)

![image](https://user-images.githubusercontent.com/15850216/31143586-4c66bf18-a843-11e7-8a2b-5a06a96d6b90.png)

![image](https://user-images.githubusercontent.com/15850216/31143722-cb6f0dc4-a843-11e7-8782-ad46c5a4f71f.png)

I have another example below which is the device sending a heartbeat packet (0x13) but traccar changes 
ignition state from "YES" to "NO" based on that packet; but the heartbeat packet does not contain any ignition information. The previous ignition state was "YES"

![image](https://user-images.githubusercontent.com/15850216/31146397-2d11c1ea-a84c-11e7-9d9c-4d073251e8a9.png)

![image](https://user-images.githubusercontent.com/15850216/31146485-8c5da81c-a84c-11e7-93c1-ee6587e4e12e.png)

![image](https://user-images.githubusercontent.com/15850216/31146468-7984d184-a84c-11e7-8660-9181284dc68c.png)

**Comment by MarcioBRSP** [comment]
Hi 
socstur , its Marcio here,at this moment I cant help you, Im trying to start to build a new server to work with GT06, I got the protocol for it, but Im unable to read the data from gps, I already made a server for tk102 tk103 and its working very well,but the protocol for GT06 is binary, Im using VB6 (yes, its old), but I have no id of how to read the data from this device, ive changed the winsock to read the data in byte or byte() but I dont know what Im doing wrong because I cant read the data, I only get values likes "?c???????". can you help me with the first conection of data sent from terminal? any help from you it would be very very useful for me, thanks a lot

**Comment by tananaev** [comment]
@MarcioBRSP, GT06 is a binary protocol, so you can't convert message into readable text.

Please don't spam everywhere with your questions. This is inappropriate place to ask. If you have any further questions please ask on forum.

**Comment by durgamanil** [comment]
i am little bit confused to send values on server in hex format..
can you please share how to send the values in hex format to server.
