### ISSUE TITLE
Laziness XSsupport

### ISSUE THREAD

**Issue by Turbovix** [traccar/traccar#3585]
I think people confuse free software with I'm here to answer you!
There is no work to be done on a subject related to the Traccar!
Many of the questions have been discussed many times ... Here I have never seen anyone asking how to contribute to the project. So #Anton, you should start filtering certain messages. Those who do not have any wisdom about the Software or Java, should hire their services / support to suit their needs.

**Comment by tananaev** [comment]
I think you are right and naturally the time will come when I just won't have enough time to answer silly questions. Even at this point I spend significant portion of my free time answering emails and forum questions.

**Comment by Turbovix** [comment]
First, Github is a tool for code contribution, so basic matters should be dealt with in the forum!

**Comment by Turbovix** [comment]
I see that you spend a lot of time dealing with basic issues, nobody wants to search the forum and find the solution. The Traccar works perfectly, but everyone feels that you receive some recourse from God ....

**Comment by tananaev** [comment]
I don't really see the point. How does having second repository help? If you or someone else wants to help, you can already do it by answering questions.

**Comment by tsmgeek** [comment]
Because it's full of open tickets, no tags to group tickets up, close old
or tickets that are superceded or fixed. You said you don't have the time,
delegate some admin to others on the issue tracker and you keep control of
the main repo.


On 20 Oct 2017 23:36, "Anton Tananaev" <notifications@github.com> wrote:

I don't really see the point. How does having second repository help? If
you or someone else wants to help, you can already do it by answering
questions.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tananaev/traccar/issues/3585#issuecomment-338338094>,
or mute the thread

**Comment by tananaev** [comment]
As I said, there is nothing that stops you from helping. I don't see any need for a separate repository. If you see tickets that should be closed that just connect on them that they can be closed.
