### ISSUE TITLE
Feature Requests HTTP SMS

### ISSUE THREAD

**Issue by kjetilpp** [traccar/traccar#3636]
Hello! 
I miss a function in traccar.

In gps-server.net you can use HTTP Api from "any" bulk sms provider. 
See: ![skjermbilde](https://user-images.githubusercontent.com/5620578/32735910-61751cce-c896-11e7-9789-9f8da3a0aaaa.PNG)

Perhaps this could be implemented together with SMPP, that already exists?

**Comment by tsmgeek** [comment]
SMPP already exists, look at the configuration file https://www.traccar.org/configuration-file/

**Comment by tananaev** [comment]
@tsmgeek, I think you have misread something.

**Comment by tsmgeek** [comment]
Yup I did, woops.
#3624 seems to be part way to this but he will not implement this as a Notification handler instead.

**Comment by Shinryuken** [comment]
It could be done eventually but GET requests are not supported on the actual implementation.

(the example shown is sending passwords using a GET?, really?)

**Comment by pc500** [comment]
This actually appears to be good idea.  Ideally, we'd all use SMPP, but the commercial availability of this product is mostly inter-carrier in nature and not carrier-to-enterprise. 

The APIs are fairly simplistic.  Almost all offer http get and post for simplification, and most offer JSON if one wants to do it correctly.    Since many non-coders are writing scripts to use there things, and you are sending a 160 character message, there is nothing that horrible about encoding it in the HTTP request:

EG:
https://api.onesimcard.com/corp.php?user=XXXX&key=XXXX&command=sms&simcard=372

Support for a couple of the basic large providers  (IE: Twileo) for the proper JSON APIs would be great, but if you offer a way to simply to a http get/post and perform variable substitution based on attributes in the DB already for the user, it shouldn't be too bad.

Passwords over get are OK as the url is encoded in SSL.  However, keep in mind, this is only SMS.

**Comment by kjetilpp** [comment]
Yes, that's one of the reasons I want this feature. It is not easy to get an SMPP account if you do not send over 20000 SMS in a month.

**Comment by tsmgeek** [comment]
To throw a spanner in the works #3651 seems to want the ability (per user) basis to forward SMS messages to an email address for Email2SMS gateways. This is not the same as sending emails as they use different templates.

**Comment by mauriceoduor** [comment]
For those in a hurry to implement HTTP Api, there is a work around which you can use in the meantime. I am also using it. Setup an SMS Gateway (OzekiNG) and connect traccar to OzekiNG and Connect OzekiNG to your SMS Provider via HTTP Api. It works and it working for me. My setup Traccar 3.15, Nominatim Geocoder, OzekiNG 3.14.20, all in one VPS running Ubuntu 14, 4GB RAM, 80GB SSD.

**Comment by tananaev** [comment]
We already support HTTP SMS APIs.
