### ISSUE TITLE
Feature Request : Computted Attributes : Server Wide on Protocol basis

### ISSUE THREAD

**Issue by jaimzj** [traccar/traccar#3824]
I would like to share a new feature request for discussion purpose, which could be considered if found viable or useful.

1. The ability for Admin users to assign a 'computed attribute' to a protocol by which it gets applied server wide.

- This will help admins / users not have to re-create and assign 'computed attributes' for all accounts/devices.

I am sure there might be downsides of this, however

This can be used in situations where the admin has a computed attribute which needs to be assigned to all devices.  (Ideally it should be allowed to only assign on protocol level and not server wide.)

 Example : I had a device for testing that uses meiligao protocol, for which traccar did not display Ignition however it had the value under 'status' so the need to use Computed attribute arise'd.

I do see a potential issue, that a different device using this protocol could behave differently with the said computed attribute (this could be discussed..as well, I do not have a solution for it though.).

**Comment by charliewillemson** [comment]
Hi

I have thaught about same thing that it would be very nice if it there is possible to use server wide computed attributes. Maybe solution would be to have option to link computed attributes directly to devices or directly to protocol?

At the moment the procedure is following: (?)
1)Admin creates computed attribute
2)Admin links computed attribute to user(s) and/or group(s).
3)User must link available computed attribute to each device he sees on the list.

If you have many users and many devices then you have to do lot of clicking before all computed attributes are linked to right users and devices.

Another big issue thing is that when you have "device readonly" premission users then they dont have possible to link that computed attributes to device because of missing premissions. In my case i have all users "device readonly" to avoid scenario that user deletes device. Restoring that data is not very simple.

Same issue occurs with geofences that you can not link them to devices. Anyway it is strange that user with "device readonly" premissions can create geofences but can not link geofence to device. 

Maybe it is all about i am not enough compentent to use and manage traccar server but can someone confirm or reject my complaints?

Thank you for good job you have done with traccar so far!

**Comment by tananaev** [comment]
You can assign computed attributes to groups of devices. As for the protocol, you can check protocol type directly in the attribute and only apply logic for the right protocol. If it doesn't work, let me know.
