### ISSUE TITLE
Removing async HTTP client

### ISSUE THREAD

**Issue by tananaev** [traccar/traccar#3905]
Commit: 5a9811c3771d92832c9bba718b5ec935844978e8.

Reasons:

1. It's an extra unnecessary dependency.
2. It uses Netty 3 and I want to try to upgrade to Netty 4 at some point.
3. We have a better alternative (`javax.ws.rs.client`).

@Abyss777, what do you think? Can you help me with testing it? I have done some basic testing of reverse geocoding and it works. Ideally I want to test all the functionality to make sure I didn't break anything.

@Shinryuken, I have tried to migrate `MultiPartEventForwarder`, but it was more complicated than I expected. If you are interested to convert it to new HTTP client, feel free to send a pull request. Note that there is a pull request #3830 in progress which will potentially make notifications system more flexible.

Feedback from anyone else is also welcome.

**Comment by Abyss777** [comment]
@tananaev 
I like it, looks like it using it become a bit simpler. 

I also tested reverse geocoding and event forwarding - work OK, what else to test geocoding and position forwarding?

**Comment by tananaev** [comment]
I also like it. Makes things cleaner.

Remaining things to test:
- Geocoding
- Position forwarding
- Statistics upload

By the way, do you think you can help me with Netty 4 upgrade? I have already started on the other branch. There will be massive amount of work. We need to update all frame and protocol decoders.

**Comment by Abyss777** [comment]
I hope I can help.
I've found one doc for migration https://netty.io/wiki/new-and-noteworthy-in-4.0.html could you recommend any other to understand better?

**Comment by tananaev** [comment]
Migration of everything except decoders is done. I got GPS103 decoder working. Tested it by removing everything else. I will create a separate thread with details tomorrow. I will also work on migrating protocols, so we can split the work.

**Comment by Abyss777** [comment]
We have some problem (or not) related to this changes.
Trips and Stops reports likely failed because of "Rate Limited". I'm using free locationiq.org (nominatim).
If I wrap all `getAddress()` https://github.com/traccar/traccar/blob/master/src/org/traccar/reports/ReportUtils.java#L199
lines in `try/catch` reports generation not fails but addresses are with gaps (one filled, three empty).

Firstly, we should add catching geocoding exceptions.
Secondly, do you think we should handle this something like synchronous reverse geocoding?

**Comment by tananaev** [comment]
Not sure what the best option is. What was happening on previous version?

**Comment by parveenkumardeeva** [comment]
Reports were also failing into the previous version due to geocoder on demand feature.

BTW, in the 
https://github.com/traccar/traccar/blob/220a912c1b4f12c4ad0d229e91ed9fd72f4aa327/src/org/traccar/geocoder/JsonGeocoder.java#L91
line we are calling CallBack Success and then again into the handleResponse method
https://github.com/traccar/traccar/blob/220a912c1b4f12c4ad0d229e91ed9fd72f4aa327/src/org/traccar/geocoder/JsonGeocoder.java#L59

Is it right? or I misunderstood something?

**Comment by Abyss777** [comment]
Silently makes gaps in addresses (but looks like less).

May be better revert this catch? https://github.com/traccar/traccar/commit/5a9811c3771d92832c9bba718b5ec935844978e8#diff-2629aa9955fa560944c6982fbb7bd5a8L110

**Comment by tananaev** [comment]
I guess we should revert, but what exceptions to catch?

**Comment by Abyss777** [comment]
In this particular case it is `javax.ws.rs.ClientErrorException: HTTP 429 Too Many Requests`

**Comment by tananaev** [comment]
I have added a catch for the exception. Also, removed `onSuccess` call which was done twice. Please check the code and let me know if you see any issues.

**Comment by Abyss777** [comment]
Perfect, thanks.
Behavior is as it was now.
