### ISSUE TITLE
Feature request: enable and disable protocols in traccar.conf

### ISSUE THREAD

**Issue by leifnel** [traccar/traccar#3991]
Usually default.cml should not be edited, but is currently the only way to disable protocols.

I suggest having this in traccar.conf
`<entry key='protocols.disable'>prot1,prot2,prot3..</entry>` then all others were enabled
`<entry key='protocols.enable'>prot4,prot5...</entry>` then all others were disabled.

**Comment by deisi** [comment]
one up for this

**Comment by victorferreira** [comment]
It think it's a really good idea, but maybe we should only have one of the options. Enable or disable, instead of both. This way we don't risk putting the same protocol in both options and end up having a problem hard to debug. 

Since all protocols are enable by default, I'd prefer to have only the disable option. What do you guys think?

**Comment by oliv3** [comment]
I'd prefer having all protocols disabled by default, so that you have to explicitely enable those you need.
There are more than 100 protocols, and I don't think a typical installation uses all of them.
Of course this should be documented, and/or maybe set OsmAnd enabled by default since new users tend to use it with Traccar client.
And/or provide a list of the most used protocols to date, dunno if this is part of the statistics sent to traccar.org when the server "phones home".

**Comment by victorferreira** [comment]
In my experience, people tend to choose very few types of devices and stick to those. Which means, at most, a handful of protocols to activate. I'm curious to learn about others experiences.

**Comment by leifnel** [comment]
How if no &lt;entry key='protocols.enable'&gt;prot4,prot5...&lt;/entry&gt;, then all protocols are enabled, otherwise only the listed ones.

**Comment by deisi** [comment]
@leifnel I think that sound very reasonable. From a user perspective it is good if all protocols are enabled by default: This way I don't have to deal with finding out the right one and enabling it in the beginning, however this would give me the flexibility of hardening/simplifying my already running system at a later point in time.

**Comment by tananaev** [comment]
Implemented a new config parameter for this. Usage example:
```xml
<entry key='protocols.enable'>osmand,teltonika</entry>
```
