### ISSUE TITLE
 GlobalSat TR-313 only fails

### ISSUE THREAD

**Issue by kuon5675** [traccar/traccar#4052]
Only GlobalSat TR - 313 will result in an error and will not be displayed properly.

Since GTR - 388 is displayed correctly, it seems that there is a problem with message analysis.

TR - 313 
```
GSr,,123456789012345,00,5,3,140918,000010,E12029.8280,N2059.4704,0,0.63,266,4,1.8,13,3*56!
```
error
```
2018-09-14 08:32:56  WARN: [5456dddd] error - For input string: "E1" - NumberFormatException (... < GlobalSatProtocolDecoder:108 < *:239 < ExtendedObjectDecoder:51 < ... < WrapperContext:102 < ...)
```

GTR - 388 
```
GSr,GTR-388,123456789012345,0000,7,8000,3,130918,235644,E12029.1204,N2059.2353,74,3.24,344,8,1.0,4310mV,0,0,14*11!
```

**Comment by tananaev** [comment]
Have you configured format strings?

**Comment by yo-konishi** [comment]
I did not register because I could do GTR - 388 without registering.

Is not it possible to make MAP display look if you specify the port?

**Comment by tananaev** [comment]
@yo-konishi, please explain how your question is related to the topic.

**Comment by yo-konishi** [comment]
I think it's the same trouble as https://github.com/traccar/traccar/pull/2451.
I think there is a problem with message analysis.
As a result, I think that information will not be displayed on the map.
As far as errors are concerned, it seems that there is a problem with "src/org/traccar/protocol/GlobalSatProtocolDecoder.java".

I write sample of information sent from terminal and error content, so can not you understand this?

**Comment by tananaev** [comment]
I'm asking you last time how your comments are related to this specific topic.

**Comment by yo-konishi** [comment]
It was the same phenomenon on this page.
I also get an ERAIL at TR - 313.
It is just a matter of not being able to analyze the message against the new hardware of "GlobalSat".

**Comment by tananaev** [comment]
OK. Have you read my first comment? What format strings have you configured?

**Comment by yo-konishi** [comment]
What does setting mean?


`src / org / traccar / protocol / GlobalSatProtocolDecoder.java`
As it sees, it is an error because it is not in the following format.

```
GSr,model,IMEI,Device_Mode,Report_Type,Alarm_Status,Geofence_status,GPS_F ix,UTC_Date,UTC_Time,Longitude,Latitude,Altitude,Speed,Heading,Numbe r_of_Satellites,HDOP,Battery_capacity*checksum!
```

The format is changed from TR - 313, but it seems that the program can not follow.

**Comment by tananaev** [comment]
Format needs to be configured in the configuration file. Have you done it? If not, obviously it won't work.

**Comment by tananaev** [comment]
You need to configure format strings on the server side to match your device settings.

**Comment by yo-konishi** [comment]
The concrete method is not described.

Also, other models can be done properly and new models are not made.

In the first place, even if you do not write it on other models, you can do it.
Only this model can not be done.

Also, as far as errors are concerned, it seems only to be a situation where there is a bug in the part of source code analysis, why does not it approve it?

**Comment by yo-konishi** [comment]
I see an error in the following place, are not you?
```
error - For input string: "E1" - NumberFormatException (... < GlobalSatProtocolDecoder:108 < *:239 < ExtendedObjectDecoder:51 < ... < WrapperContext:102 < ...)
```


Is it an error in the protocol analysis section?


Even at https://github.com/traccar/traccar/pull/2451, it was pointed out that there are new ones, and you tried modifying GlobalSatProtocolDecoder.java, right?

Unfortunately it seems not completed

**Comment by tananaev** [comment]
The issue that you are keep referring to is **ancient**. Protocol has been change many times after that.

**Comment by yo-konishi** [comment]
It does not occur in GTR - 388 as it is pointed out in the upper part of the reality problem, it occurs in TR - 313.
As long as you see the messages listed above, you notice that one item is getting less.
I am getting the same error.
Also, if it is fixed it will be different from GTR - 388, so errors should occur in GTR - 388, but it has not happened.

**Comment by tananaev** [comment]
Do you have protocol documentation for your device?

**Comment by yo-konishi** [comment]
@tananaev 

Even gpsgate seems to make the protocol different because messages are different.
https://forum.gpsgate.com/viewtopic.php?t=11491

Based on that fact, I confirmed to the developer and I received the following answers.

As it was said in old products and new products, there are differences.

```
Old product
```
GSr,Device_ID,IMEI,Alarm_status,Report_Type,Variable_field,GPS_Fix,UTC_Date,U TC_Time,Longitude,Latitude,Altitude,Speed,Heading,Number_of_Satellites,HDOP, main_battery_voltage,backup_battery_voltage,analog_input_value,odometer_valu e,GSM_signal_strength,cell_ID_MCC,cell_ID_MNC,cell_ID_LAC,cell_ID_CID*check sum!

```
new product (GlobalSat TR-203, TR-600, GTR-128, GTR-129, TR-313・・・)
```
GSr,Device_ID,IMEI,Device_Mode,Report_Type,Alarm_Status(option),Geofence_status(option),GPS _Fix,UTC_Date,UTC_Time,Longitude,Latitude,Altitude,Speed,Heading,Nu mber_of_Satellites,HDOP,Battery_capacity*checksum!


So it became clear that it does not correspond to the current product as the sentences and errors written at the beginning of issue.

**Comment by tananaev** [comment]
I would need proper protocol documentation.

**Comment by yo-konishi** [comment]
Then I think that you should contact GlobalSat

**Comment by yo-konishi** [comment]
By the way, it is below the TR - 203 that is not the latest version.

http://www.globalsat.ru/Sites/global/Uploads/TR-203_Development_Document_Version_2.6_160606% 28eng.% 29.3438F3B677C64460A31DE8137D280058.pdf

After that, please feel free to GlobalSat.

**Comment by yo-konishi** [comment]
@tananaev 

By the way, it is below the TR - 203 that is not the latest version.

```
http://www.globalsat.ru/Sites/global/Uploads/TR-203_Development_Document_Version_2.6_160606%28eng.%29.3438F3B677C64460A31DE8137D280058.pdf
```
After that, please feel free to GlobalSat.

**Comment by tananaev** [comment]
OK, I'm a bit tired of arguing. If you think there is a bug, here is what I need:

1. Log fragment with HEX data from your device.
2. Protocol document specifically for your device model.
3. Configuration parameters that device uses (unless it's fixed and specified in protocol document).
4. Configuration parameters that you specified for GS protocol in server config.

**Comment by yo-konishi** [comment]
At least it can not be changed as the facts below.
- At least the same person has the same error.
- Different projects have different formats because format is different

I can not understand honestly not to look directly at these bugs.

I wrote a lot of information, though I thought that it would be better for a person with the same problem to get better at least a little traccar, but I also got tired.

Since I do not have a maintenance contract etc., I do not know whether it can deliver it even if gotten from globalsat and I will stop discussing because I think there is no improvement as I will not face the reality.

**Comment by tananaev** [comment]
1. I don't see the bug.
2. Format is configurable.

**Comment by wataruSakurai** [comment]
I have used TR-313j too. This is not the bug. @yo-konishi  -san, you should edit configuration for data format and access port from the device.
I think that you need below configuration.

```
cat > /opt/traccar/conf/traccar.xml << EOF
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>
<properties>
    <entry key="config.default">./conf/default.xml</entry>
    <entry key='globalsat.format0'>SORPZAB27GHKLMN*U!</entry>
    <entry key='globalsat.port'>5000</entry>
</properties>
EOF
```
