### ISSUE TITLE
[Feature Request] Allow use of BingMaps OSGB layer

### ISSUE THREAD

**Issue by captain-paranoia** [traccar/traccar#4108]
For outdoor tracking applications in Great Britain, it would be nice if the BingMaps OSGB mapping layer could be selected as the base mapping. This mapping layer is much more appropriate for outdoor activity use than the urban road mapping layer.

I understand that the user base would be limited to outdoor users in Great Britain only, but, looking at the BingMaps API, it doesn't look that difficult to request the OSGB layer. I'd have a go at modifying the code myself, but I've had a look, and am struggling to find even where the BingMaps API is implemented, let alone how to modify it...

**Comment by tananaev** [comment]
We do support Ordnance Survey maps in the modern app.

**Comment by rallycivic** [comment]
Bing provides access to the Ordnance Survey 1:50,000 and 1:25,000 scale leisure maps which are the same as the printed maps we can buy in Great Britain. I get that with a "style=s" in the URL:
https://www.bing.com/maps?cp=51.997671%7E0.485759&lvl=15.0&style=s&dir=21.7&pi=0.7

The Ordnance Survey maps in the modern app use the new very detailed free vector map, which is really good when zoomed right in, but unfortunately then goes blank as you zoom out. It is not what we normally think of as Ordnance Survey maps, as it is not what we buy in the shops.

The Ordnance Survey 1:50,000 and 1:25,000 scale leisure raster maps are also available from the OS with an API key, but didn't just appear when I edited the file in modern/static/js to use my key. It would be great if we could see the 1:50,000 and 1:25,000 scale maps as we zoom out from the current detailed maps in the modern app, but I would be happy with any map at all instead of a blank map.

**Comment by tananaev** [comment]
Maybe it can work similar to other Bing Maps?

https://github.com/traccar/traccar-web/blob/master/modern/src/map/core/useMapStyles.js#L120-L129
