### ISSUE TITLE
Tracker server log

### ISSUE THREAD

**Issue by Nyamazane** [traccar/traccar#413]
Dear Tananaev..... could you please tell me how to open Tracker server log...my PC says   ...windows does not recognize file....
Thank you very much
Victor Hugo

**Comment by hako2008** [comment]
the problem is when we activate the GPRS mode and change the server, we receiving a unclear messages, otherwise it's sending the information correctly to gprs110.org.
you can check the attached photos, and it's compared with another device that clearly posting a HTTP variables.
![tk110](https://user-images.githubusercontent.com/16450992/46908406-38922000-cf1a-11e8-8f2b-5da33dcf069d.png)
![tk2007921744](https://user-images.githubusercontent.com/16450992/46908407-38922000-cf1a-11e8-9497-37b650d59772.png)
![2](https://user-images.githubusercontent.com/16450992/46908408-38922000-cf1a-11e8-873d-79ef371bf5db.png)
![adminip ok](https://user-images.githubusercontent.com/16450992/46908409-38922000-cf1a-11e8-89ac-535588cc6e4a.png)
![check](https://user-images.githubusercontent.com/16450992/46908411-392ab680-cf1a-11e8-9c6b-ede1fba4a6a4.png)
![gprs ok](https://user-images.githubusercontent.com/16450992/46908412-392ab680-cf1a-11e8-93de-f34e75c75f47.png)

**Comment by mota2007** [comment]
Talk to me the same thing that sends words incomprehensible. I need help
