### ISSUE TITLE
Upgrade from 3.16 to 4.4

### ISSUE THREAD

**Issue by mr2017x** [traccar/traccar#4304]
Hi Guys,

trying to sign in to your forums doesn't work (cant register) so i hopefully asking here.

I want to upgrade from 3.16 to 4.4 i saw that i need to place a step between but at 3.3 it says that table users(something) is already present. therefore that doesnt run. Maybe you can give me the trick for worry free upgrading

1. Backup, backup, backup (VM, Snapshot, nice!) 
2. cp -r /opt/traccar /opt/traccar_bkp
3. wget 3.3-lin64, unzip 
4. rm /etc/init.d/traccar for possiblity to reinstall
5. /traccar.run for new install with 3.3
either service traccar start or /opt/traccar/bin/traccar - both doesnt run.

i also tried to completely delete /opt/traccar before with rm-rf also doesn't run. 

So where is the problem, how can i deal with it?

And furthermore, i sadly have a wellplayed h2 Database, is it possible to migrate it to mysql without hazzle via your programm? (or getting the information towards mysql?)

Thanks in advance and have a nice evening.

**Comment by tananaev** [comment]
For questions there is forum. GitHub is only for development related discussions, not for general questions.

As for your question, you don't need to DOWNGRADE to version 3.3, obviously. You only need to UPGRADE to it if you use versions lower than 3.3. If you are not very familiar with software versioning, 3.16 is higher than 3.3 because minor version 16 is higher than 3.
