### ISSUE TITLE
traccar.service: Failed at step EXEC spawning /opt/traccar/jre/bin/java: Exec format error

### ISSUE THREAD

**Issue by m0o0hammad** [traccar/traccar#4321]
Thank you for your excellent server
Please follow the instructions below.
Thanks
![Screenshot from 2019-05-23 00-59-51](https://user-images.githubusercontent.com/30108318/58206750-967bb700-7cf6-11e9-8dd3-4e6063bb5765.png)

**Comment by tananaev** [comment]
Probably bundled JVM is incompatible. Try using system one.

**Comment by m0o0hammad** [comment]
Thank you for your guidance. But I installed an older version of 3.9 without problems

**Comment by tananaev** [comment]
Try running manually and see what the problem is.

**Comment by mqmq0** [comment]
I got the same issue with a fresh install:

`● traccar.service - traccar
Loaded: loaded (/etc/systemd/system/traccar.service; enabled; vendor preset: enabled) 
 Drop-In: /etc/systemd/system/traccar.service.d   
 └─run-as-user.conf   Active: failed (Result: exit-code) since Fri 2019-05-24 15:04:50 CEST; 19min ago  
 Process: 22934 ExecStart=/opt/traccar/jre/bin/java -jar tracker-server.jar conf/traccar.xml (code=exited, status=203/EXEC)
 Main PID: 22934 (code=exited, status=203/EXEC)
 May 24 15:04:50 opi systemd[1]: Started traccar.
 May 24 15:04:50 opi systemd[22934]: traccar.service: Failed to execute command: No such file or directory
 May 24 15:04:50 opi systemd[22934]: traccar.service: Failed at step EXEC spawning /opt/traccar/jre/bin/java: No such file or directory
 May 24 15:04:50 opi systemd[1]: traccar.service: Main process exited, code=exited, status=203/EXEC
 May 24 15:04:50 opi systemd[1]: traccar.service: Failed with result 'exit-code'.`

Running the server manually works with 
`java -jar tracker-server.jar conf/traccar.xml`

Maybe unrelated, but:
Now its runs with its own DB, but I tried to use mysql, based on the 

> https://www.traccar.org/install-digitalocean/

config.

I got the following error:

`Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.        at org.traccar.Main.main(Main.java:104)Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. `

**Comment by m0o0hammad** [comment]
I'm manually building it that I encountered the following error:
unable to create file '/run/user/1000/dconf/user': Permission denied.  dconf will not work properly.

my machine:
Linux mohammad 4.9.0-7-686-pae #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) i686 GNU/Linux
@mqmq0 @tananaev

**Comment by evmo** [comment]
I had this same issue after a fresh install of 4.5. Make sure your database password doesn't have a "&" symbol in it.
