### ISSUE TITLE
FM5400 TCP COM Link

### ISSUE THREAD

**Issue by MikyKuroneko** [traccar/traccar#454]
I have a Teltonika FM5400 device that includes two RS232 ports, both supporting TCP COM Link. As per Teltonika support team explanations, when set in this mode everything received from these ports is sent back to the server (encoded in their standard encoding, of course, but without AVL format). I've done a few tests and the data seems to arrive, but Traccar closes the connection on a exception (expects 5 bytes, receives 4, I think).

Would it be possible to support this mode?

Thank you.

**Comment by Aciid** [comment]
@tananaev what's the direction of Traccar? As it stands it's a receiving logging server, would full featured fleet management improvements be appreciated? I understand that it would require a full rewamp of the architecture.

**Comment by tananaev** [comment]
@Aciid,

First of all, how is your question related to the topic? If it's not, please create a separate thread.

As for the question, what features do you expect to see in "fully features fleet management"?

**Comment by Aciid** [comment]
Regarding to codec 12, it is be possible to acquire more data over established communication channels after acknowledging the AVL packets.

As for the question, I mean if traccar would work more like a framework than a drop-in app, this kind of stuff would be rather easy to plugin.

**Comment by tananaev** [comment]
I will add support for data without location info in future versions.

Can you please be more specific about what framework means in this case. Also, an example of fully features fleet management system would be great.

**Comment by Aciid** [comment]
Maybe I was exaggerating on the "full featured".. what I meant was, are you interested in going further than just logging with the project. 

Given that some if not all more recent devices have capability of parsing incoming packets as well, traccar could query "user" requested packages on connect. I'm fairly sure that this would unlock potential on devices so they could be used to their fullest extent if needed.
As for the framework part. I guess people have different use cases, but one familiar would be traccar as a backend server for other apps to query stored data via an API endpoint. I see that traccar has been a one mans epic journey and all props on that theres a huge amount of supported protocols. I dont know why im still even writing and wasting your time with this. I'll just fork sorry.

**Comment by tananaev** [comment]
I plan to add more features to the web interface very soon. Support for commands is coming as well. I am in the middle of rewriting web interface and server API, so there will be API (better than GWT RPC) that other apps could use.

**Comment by Aciid** [comment]
Sorry to push this issue again. But I accidentally stumbled here because I was looking for actual teltonika things and there literally is no communities regarding to business cases.

About Codec 12 & AVL packets. Teltonika is protective about it, because chinese manufacturers want to copy everything that's available in the internet. Including comments in these discussions.

Codec 12 reference costs around 100€ I suggest every end developer buy it to support the company. 
@LimitTech  https://github.com/tananaev/traccar/issues/454#issuecomment-36977773 was on the right tracks, yes the codec format is decodable without the reference.

Also @tananaev I'm still following traccar. My case involves 2-way communications so I've made some tests regarding that on traccar. Implementing [drools](http://www.drools.org/)  requires a ESB or a working API for both. So i'm still drawing things on paper =)

Thanks for all the great work, I'll be here making some noise once I get things moving forwards, but my timespans are long.

**Comment by tananaev** [comment]
I would always prefer companies with more open policy towards their communication protocol. I think they will benefit from it in the long term.

**Comment by tananaev** [comment]
I have added support for codec 12 to Traccar.
