### ISSUE TITLE
Push Positions to Unix Domain Socket instead of TCP/IP port

### ISSUE THREAD

**Issue by heisGarvit** [traccar/traccar#4623]
We want to push all positions data to post request UNIX domain socket instead of post request on port. Can you please guide us for the same.
Current configuration:
```xml
<entry key='forward.enable'>true</entry>
<entry key='forward.json'>true</entry>
<entry key='forward.url'>http://localhost:8084</entry>
```
Needs something link this:
```xml
    <entry key='forward.url'>http://unix:/home/user/unix.sock;</entry>
```

Reason:
Reduce TCP/IP overhead

**Comment by tananaev** [comment]
Forwarding is HTTP-based, so I don't think what you're asking is possible.

**Comment by wucke13** [comment]
@tananaev you are wrong, HTTP can totally go over UNIX domain sockets. For example, `systemd-socket-proxyd` can easily interpose between services/clients which either expect a socket file or a IP + port for TCP traffic. This is really nice for example to use UNIX domain sockets to pass traffic across (otherwise completely isolated) network namespaces.

I just found this issue to see if there is a documented case of using `junixsocket` to connect to Postgres via UNIX domain socket, removing all the TCP/IP and username + password cruft. For services that colocate on the same machine, I much prefer not having to deal with credentials, allocating a port, etc.. Just making the UNIX domain socket file accessible for the database client app is leaner, scales better (no port allocation problem) and has fewer security implications (did my credentials leak, do I need to rotate them, ...) while being a little more efficient. But, that's a different story.

However, that defeats the purpose of @heisGarvit on reducing TCP/IP overhead.

**Comment by tananaev** [comment]
Obviously you can have some proxy. My statement is about what is supported out of the box currently.
