### ISSUE TITLE
Token-based url authentication does not work on modern ui upon first connection

### ISSUE THREAD

**Issue by darkmattercoder** [traccar/traccar#4678]
Closing this, as I did not really understand everything.... sorry for the noise

**Comment by gangelop** [comment]
Not sure why you closed this issue because the problem still exists.

When I visit `/?token=XYZ` I get redirected to `/modern/login`. If I click the button on the upper right to "switch to legacy app" and then visit `/?token=XYZ` it works, within the old app. If *after doing this* I switch back to the new app, it continues to work.

**Comment by tananaev** [comment]
It looks like you're not using the latest version.

**Comment by gangelop** [comment]
Thanks and sorry. I thought I was on 5.3 but I was on 5.2.
Now I'm facing a different token-related issue in 5.3. I'll look into it and open another issue if applicable.
