### ISSUE TITLE
See battery level on traccar with h02 protocol

### ISSUE THREAD

**Issue by amibumping** [traccar/traccar#4757]
I own a Sinotrack ST-905 that uses h02 protocol and I am seeing that on sinotrack platform I'm able to see battery level. Is is possible to see that information on traccar?

**Comment by juniormelo26** [comment]
It will probably be necessary to do some Volt conversion to the % equal to the suntech backup battery. Now you need to know which parameter corresponds, in the Suntech documentation it shows, I don't understand this sinotrack.

![baaterry-suntech](https://github.com/traccar/traccar/assets/22121703/c72c92f9-d254-4037-89bc-7dd673dea098)

**Comment by Turbovix** [comment]
@amibumping  a while ago I was banging my head about this, and as not was successful, I ended up abandoning it. Now the idea came to me whether the value reported on the Sinotrack server is real. Try removing the battery or checking when it is fully charged or empty and see what the Sinotrack platform says. If it does in fact report the correct battery status, the documentation is missing that.

**Comment by Twenty2a** [comment]
I've been doing some work on a Sinotrack ST-904 and have found the following with the help of Claude analysing the position data from a couple of devices.
Computed Attributes can then be used to convert these values into the relevant field to display in the interface.

| Field | Inferred meaning | Evidence |
|---|---|---|
| `io1` | **MCC** (mobile country code) | Only two values across both units: `000` and `234`. `234` is the UK's MCC. |
| `io2` | **MNC** (mobile network code) | Only two values: `00` and `30`. `234-30` is a real, registered PLMN — **EE** (formerly T-Mobile UK) — confirmed via [mcc-mnc.org](https://mcc-mnc.org/networks/234_30). Moves in lockstep with `io1`: always `00` exactly when `io1` is `000`, always `30` exactly when `io1` is `234`. |
| `io3` | **LAC** (Location Area Code) | Resets to `0000` in exact lockstep with `io1`/`io2` going to `000`/`00`; otherwise one of a handful of stable 5-digit values (`24601`, `24611`, `22571`, …) — consistent with a small number of LACs covering the area the units were actually in. |
| `io4` | **CID** (Cell ID) | 89–144 distinct values per unit — far more granular than `io3`, exactly as expected for individual cell towers/sectors nested under a handful of LACs. Also zeroes in lockstep with `io1`–`io3` when registration is lost. |
| `io5` | **GPS satellites (in view/used)** | Range 0–22 on both units — the right order of magnitude for a satellite count. The clean tell: on the unit whose export includes invalid fixes (`deviceId 2`, 209 rows with `valid=false`), `io5` is **exactly `0` on every single one** of them, vs. an average of ~17 on the 2,535 valid-fix rows. GPS quality dropping to zero precisely when Traccar's own `valid` flag also says "no fix" is about as clean a confirmation as this kind of reverse-engineering gets. |
| `io6` | **GSM/cellular signal strength**, most likely a `0`–`31` CSQ-style scale | Range is `0`–`31` on both units — matches the standard `AT+CSQ` signal-quality scale (0 = no signal, 31 = strongest) used across GSM/LTE modules generally. `io6 == 0` occurs a handful of times on each unit and **only ever** when `io1`/`io2`/`io3`/`io4` have also collapsed to `000`/`00`/`0000`/`0000` (cell registration lost) — i.e. exactly when "no signal" would be expected. The reverse isn't quite as clean (registration-lost rows don't *always* show `io6==0` — sometimes a plausible-looking value lingers, presumably a stale/cached reading from just before registration dropped), but the one-directional correlation (`io6==0` ⇒ no registration, always) across ~1,100+2,750 rows with zero counterexamples is strong. |
| `io7` | **Possibly device (internal) temperature, °C** — less certain than `io5`/`io6` | Narrow band, `29`–`41` across both units, with a repeating diurnal drift each day (lower — mid-30s — in the early-morning hours, climbing to a `~40` afternoon peak, easing back down overnight) independent of GPS/cell state. That shape fits an internal-temperature sensor (plastic tracker case, some self-heating, sun exposure) better than any signal-quality metric — 29–41°C is a plausible *internal* reading even on a mild UK September day. Not corroborated by anything in either manual (§9/§10) beyond the protocol spec having a "Temperature alarm" bit and a dedicated temperature slot in the *other*, non-fallback branch of the same field — so plausible, not proven. |
| `io8` | **Battery level, %** | Confirmed by long-run correlation with expected discharge behaviour — `1`–`100` range holds up across both new exports too, including a clean run down to single digits/`1` on one unit |
