### ISSUE TITLE
Calculating Idle Time

### ISSUE THREAD

**Issue by mail2bishnoi** [traccar/traccar#4781]
Hi Anton,

Idle time = For how much time the device is standing at the same location. However, the device is reporting at regular intervals.

I would like to add idleTime  attribute in position.attributes. If you allow me to merge, I can open a PR for this feature.

Thanks

**Comment by tananaev** [comment]
I would need more details on how you plan to implement it.

**Comment by iceberg1369** [comment]
It is also nice to fire idling alert by setting a value

**Comment by mail2bishnoi** [comment]
Hi Anton,

I am planning to implement it like DistanceHandler. Comparing location data (latitude, longitude) in the last position with the location data in the current position. If location data is the same then we can calculate the difference between serverTime/deviceTime and store it in the position.attributes.idleTime. Something like below

double idleTime = 0.0;
double totalIdleTime = 0.0;
Position last = identityManager != null ? identityManager.getLastPosition(position.getDeviceId()) : null;
if (last != null) {
 totalIdleTime = last.getDouble(Position.kKEY_IDLE_TIME);

if (last.getLatitude() == position.getLatitude() && last.getLongitude() == position.getLongitude()) {
 idleTime = calculateIdleTime(last.getServerTime(), position.getServerTime());
totalIdleTime  = totalIdleTime  + idleTime;
} else {
 totalIdleTime = 0.0;
}
}

position.set(Position.KEY_IDLE_TIME, totalIdleTime);

**Comment by tananaev** [comment]
This is not a good solution. You need to use motion. Also, idle only makes sense when ignition is on. You also probably want to have some threshold, so you don't count things like traffic light stops as idle.

**Comment by mail2bishnoi** [comment]
Hi Anton,

I'll address your comments, this is what I am planning to start with.

**Comment by emrahevlek** [comment]
Hi @mail2bishnoi.
This code is not heallthy! Because device sending not same positions (lat,lon). **I developed gps tracking system not traccar!** I used this struct.
So Sample, 
You declared waiting time so 10 seconds.
1: Device sent at time 10:00:00, lat/lng: 12.5426, 18.5074
2: Device sent at time 10:00:05, lat/lng: 12.5826, 18.5174 (**this location not same before location**)
3: Device sent at time 10:00:10, lat/lng: 12.5816, 18.5064 (**this location not same before location**)

If you use distance it can works fine. Because positions are changing every locations. 
So sample:
Declare 10 meters and 10 seconds

1: Device sent at time 10:00:00, lat/lng: 12.5426, 18.5074
2: Device sent at time 10:00:05, lat/lng: 12.5826, 18.5174 (**this location not same before location but meter <10**)
3: Device sent at time 10:00:10, lat/lng: 12.5816, 18.5064 (**this location not same before location but meter <10**) create waiting alert.

**Comment by jcardus** [comment]
@tananaev, does it make sense to add idle time on EngineHoursHandler? I could open a PR for that.

**Comment by tananaev** [comment]
If we can make it configurable (and disabled by default), I don't mind adding it.

**Comment by MagedAlNaamani** [comment]
@tananaev How can enable Idle report?

**Comment by tananaev** [comment]
Someone needs to implement it first before you can enable it.

**Comment by neuvill** [comment]
Dear All, is this feature implemented?

**Comment by neuvill** [comment]
I would like to work on it if you can give me any orientation
