### ISSUE TITLE
Add a new devices

### ISSUE THREAD

**Issue by saleh2025** [traccar/traccar#4798]
hello dear

good day
can you add new device its from xexun model XT01 and other one is from eelink model TK419 can you add it in your system
thank
[XEXUN Devices and Server Data Protocol for GPS tracker from Elyssa 20210521.pdf](https://github.com/traccar/traccar/files/7881131/XEXUN.Devices.and.Server.Data.Protocol.for.GPS.tracker.from.Elyssa.20210521.pdf)
[Eelink protocol V2.1.pdf](https://github.com/traccar/traccar/files/7881132/Eelink.protocol.V2.1.pdf)

**Comment by tananaev** [comment]
Yes, we can. Please send us an email if you are interested in sponsoring the work.

**Comment by saleh2025** [comment]
Dear All

good day

What is the prosiger for that, already using the traccar system and I
ordered this device but I see it's not supported in traccar, what can we
do?
you will add it ?
waiting for your urgent reply

thanks in advance
saleh


‫في الاثنين، 17 يناير 2022 في 9:47 م تمت كتابة ما يلي بواسطة ‪Anton
Tananaev‬‏ ***@***.***‬‏>:‬

**Comment by tananaev** [comment]
What's prosiger?

**Comment by saleh2025** [comment]
Add the devices you will add it ??

في ثلاثاء، 18 يناير، 2022 في 8:08 م، كتب Anton Tananaev <
***@***.***>:

**Comment by tananaev** [comment]
I don't know if you realized that, but you didn't send an email to us. You just posted on GitHub via email.

If you are interested in sponsoring the work, send the email to the support address or to me personally.

**Comment by saleh2025** [comment]
I have to add it ?

في أربعاء، 19 يناير، 2022 في 10:56 ص، كتب Anton Tananaev <
***@***.***>:

**Comment by gustacg** [comment]
Hey guys! I have a vacancy for a project. I'm looking for someone with experience in tracking or TCP communication systems to integrate a tracker model (ST310U from Suntech) and create a page for my clients to carry out the integration in an extremely practical way. If you know someone or have this experience. Contact us at:
55 98 98554-4543

**Comment by gustacg** [comment]
I am willing to support this incredible work. However, I carried out a project from scratch because their system is not compatible with the Suntech ST310U model, and the system I am creating is for a private company, that is, the map will only be in their company. Could you enable the integration of this tracker model and create a page for integration? I would definitely sponsor it with a higher amount than I would give a programmer to do for me. (only send me the necessary information, not just include it in this entire traccar system, please)

**Comment by SebastEnn** [comment]
Devices got added to [list of supported devices](https://www.traccar.org/devices/). Issue can be closed.
