### ISSUE TITLE
How to use Postgresql in Traccar ?

### ISSUE THREAD

**Issue by andromida** [traccar/traccar#480]
Hello,

I am a beginner in using Traccar, I want to use Postgresql to store data. How can I do that ?

**Comment by ibrahims88** [comment]
Hello, I work with the Postgres database, I have a little trouble with registration in EventData table, here is my configuration: 
<entry key='database.insertPosition'>
        START TRANSACTION;
            UPDATE device SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp =   (SELECT EXTRACT(EPOCH FROM :time)::bigint)  , lastUpdateTime =  (SELECT EXTRACT(EPOCH FROM :time)::bigint)  WHERE imeiNumber = :device_id;
            SELECT @accountID := accountid, @deviceID := deviceid FROM device WHERE imeiNumber = :device_id;
            INSERT INTO eventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, creationTime, address)
            VALUES (@accountID, @deviceID,   (SELECT EXTRACT(EPOCH FROM :time)::bigint) , 0, :latitude, :longitude, :speed  , :course, :altitude, '', (SELECT EXTRACT(EPOCH FROM NOW())::bigint) , :address);
        COMMIT;
    </entry>
and i have this Error : 
 INFO: device: 357474045058001, time: Wed Jan 21 13:25:45 GMT 2015, lat: 35.71627, lon: -5.910526
 WARN: No value specified for parameter 4. - org.postgresql.util.PSQLException (SimpleParameterList.java:223)
BIGINT is not a parameter i use it to convert timestamp to bigint .

**Comment by tananaev** [comment]
I think the problem is with `::bigint`. Traccar interprets <strong>colon+word</strong> as an input parameter. You need to find another way to get time. Maybe move conversion to a separate function.

**Comment by ibrahims88** [comment]
can you  help me and tell me how to do the conversion into a separate function ?

**Comment by tananaev** [comment]
What type do you need to convert to?

**Comment by ibrahims88** [comment]
thanks for replay ;  i found a way to do it , if anyone work with postgresSQL this is the insert position i did :
 <entry key='database.insertPosition'>
         
             UPDATE device SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp =  (select  EXTRACT(epoch from now())), lastUpdateTime =  (select  EXTRACT(epoch from now())) WHERE imeiNumber = CAST(:device_id AS VARCHAR);
			WITH myconstants as (SELECT  accountid, deviceid FROM device WHERE imeiNumber = CAST(:device_id AS VARCHAR)) 
			INSERT INTO eventData (accountID, deviceID ,timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData,creationtime,  address)
            VALUES ((SELECT accountid FROM myconstants), (SELECT deviceid FROM myconstants) ,(select  EXTRACT(epoch from now())),0, :latitude, :longitude, :speed  , :course, :altitude, '', (select  EXTRACT(epoch from now())), :address);
        
    </entry>

**Comment by tananaev** [comment]
Thanks for sharing the query. The only problem I noticed is that you use `now()` instead of device timestamp.

**Comment by kokkytos** [comment]
I need to use postgresql/postgis as database engine for traccar.
1. What postgresql version is supported?
2. Does traccar web interface support postgresql.
3. Is there any step-by-step instructions to use postgresql database engine with traccar (I have installed traccar 2.11)?

**Comment by tananaev** [comment]
1. Any version should work.
2. It should as it uses Hibernate library which supports Postgres.
3. Unfortunately no, but you can try to search for more info on this issue tracker. Basically you need to change database connection parameters (Google for "JDBC Postgres URL" or something like that).

**Comment by GiSSoTesla** [comment]
<entry key='database.driver'>org.postgresql.Driver</entry>
<entry key='database.driverFile'>/opt/traccar/lib/postgresql-9.3-1103-jdbc4.jar</entry>
<entry key='database.url'>jdbc:postgresql://localhost:5432/Postgres</entry>
<entry key='database.user'>postgres</entry>
What wrong????????? 
Run application traccar.bat
wrapper.bat for x64 where found?

**Comment by GiSSoTesla** [comment]
pper  | 2015/04/30 10:58:01 | Launching a JVM...
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager: 
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager: WARNING - Unable to load the Wrapper's native library 'wrapper.dll'.
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager:           The file is located on the path at the following location but
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager:           could not be loaded:
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager:             C:\Program Files (x86)\Traccar\bin\..\lib\wrapper.dll
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager:           Please verify that the file is both readable and executable by the
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager:           current user and that the file has not been corrupted in any way.
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager:           One common cause of this problem is running a 32-bit version
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager:           of the Wrapper with a 64-bit version of Java, or vica versa.
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager:           This is a 32-bit JVM.
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager:           Reported cause:
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager:             C:\Program Files (x86)\Traccar\lib\wrapper.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager:           System signals will not be handled correctly.
INFO   | jvm 1    | 2015/04/30 10:58:01 | WrapperManager: 
INFO   | jvm 1    | 2015/04/30 10:58:02 | 2015-04-30 10:58:02.631:INFO:oejs.Server:jetty-8.1.16.v20140903
INFO   | jvm 1    | 2015/04/30 10:58:03 | 2015-04-30 10:58:03.506:INFO:oejw.WebInfConfiguration:Extract jar:file:/C:/Program%20Files%20(x86)/Traccar/traccar-web.war!/ to C:\Users\GiSSo\AppData\Local\Temp\2\jetty-0.0.0.0-8082-traccar-web.war-_-any-\webapp
INFO   | jvm 1    | 2015/04/30 10:58:06 | 2015-04-30 10:58:06.742:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
INFO   | jvm 1    | 2015/04/30 10:58:06 | 2015-04-30 10:58:06.836:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8082

**Comment by GiSSoTesla** [comment]
server:
broserver.cloudapp.net:58152 -foor rdp
login traccar
password Qwerty54321
Please help!!! Bonus is WAS!

**Comment by GiSSoTesla** [comment]
INFO   | jvm 1    | 2015/04/30 11:07:09 | 2015-04-30 11:07:09.136:WARN:/:unavailable
INFO   | jvm 1    | 2015/04/30 11:07:09 | javax.persistence.PersistenceException: [PersistenceUnit: release] Unable to build EntityManagerFactory
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:915)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:890)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.ejb.HibernatePersistence.createEntityManagerFactory(HibernatePersistence.java:57)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:63)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:47)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.traccar.web.server.model.DataServiceImpl.init(DataServiceImpl.java:66)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.init(RemoteServiceServlet.java:166)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:415)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:657)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2015/04/30 11:07:09 | Caused by: 
INFO   | jvm 1    | 2015/04/30 11:07:09 | org.hibernate.HibernateException: Connection cannot be null when 'hibernate.dialect' not set
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:97)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:67)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:170)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.service.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:75)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:159)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:131)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:77)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2276)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2272)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1741)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.ejb.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:94)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:905)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:890)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.hibernate.ejb.HibernatePersistence.createEntityManagerFactory(HibernatePersistence.java:57)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:63)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:47)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.traccar.web.server.model.DataServiceImpl.init(DataServiceImpl.java:66)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.init(RemoteServiceServlet.java:166)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:415)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:657)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/04/30 11:07:09 | 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)

**Comment by ibrahims88** [comment]
Can u show us your config file ?

**Comment by tananaev** [comment]
What version of Java and Traccar have you installed (32/64)?

As for PersistenceException problem, it means Traccar cannot connect to your database. There must be some problem with database config parameters.

**Comment by galleon1** [comment]
My postgresql 9.4 gives SQL errors when traccar QueryBuilder uses  Statement.RETURN_GENERATED_KEYS on SELECT queries.  It says that it getting an error near the statement "RETURNING *"  I looked through the Postgresql forums and there is an old known issue. 
  I used a conditional :
if(parsedQuery.contains("SELECT")){
                    statement = connection.prepareStatement(parsedQuery);
                } else {
                statement = connection.prepareStatement(parsedQuery, Statement.RETURN_GENERATED_KEYS);
                }
to fix near line 51 in QueryBuilder.java.

**Comment by tananaev** [comment]
@geogeek11, I have removed `RETURN_GENERATED_KEYS` for everything except insert queries where we need `id`. Please try and see if it works.

Are you using default Traccar database structure or your own one?

**Comment by galleon1** [comment]
Thank you for the fix on the RETURN_GENERATED_KEYS, it eliminated the error message
I'm (mostly) using the default structure,  the only 3 differences being:

1.) primary keys in the create statement had to be created with this syntax:   create table  .....   id SERIAL PRIMARY KEY   

2.) "user", "read" and "write" columns had to be double quoted because they are reserved words in Postgres sql

3.)  Double data type is Double Precision 

Everything else has worked good with defaults.

**Comment by geogeek11** [comment]
i'm sorry, i cannot test traccar right now, i'm not using it my machine.

**Comment by tananaev** [comment]
If you are using default queries, then are tested only with H2 and MySQL databases. They should be changed for PostgreSQL as its syntax is quite different.

**Comment by galleon1** [comment]
In this version, you've cleaned up the sql and moved it into the traccar.cfg and pretty much everything works now, without modification, even the new web interface.  
Only three differences:
The primary key syntax is different  "  create table.... (id SERIAL PRIMARY KEY...",  
The words "user", "read" and "write" have to be double quoted in SQL   
The Double data type is called Double Precision in postgres

No other changes.
I was surprised it worked so easily too!  Older versions were more difficult.   I've 9 castel gps units running on traccar with postgresql for over a week now.  

The castel decoder had a couple bugs but works now.   (I think you need to reverse the negative signs on the lat lon in the castel decoder. ~around line 137)

**Comment by tananaev** [comment]
Created a separate issue to track the Castel problem - #1281.

**Comment by tananaev** [comment]
There will be some changes to the queries in the next release, so I have created a page for PostgreSQL configuration:
https://www.traccar.org/postgresql/

**Comment by ismailyavuz** [comment]
It's like a postgres question but maybe we can have a standard script here about Traccar indexes.

I don't have much data (several devices for less than a month) but the query of positions last too long.

The query below takes 70 seconds to complete:
select * from positions where deviceId = 24 order by fixtime 

I created an index like this, the script completed with success in less than a second (too fast?)
CREATE INDEX IX_positions_deviceId_fixtime ON positions USING btree(deviceId, fixtime) 

But the positions query still takes too much time (no difference). Should i do anything like rebuild, reindex, restart or something like this? Or my script is wrong?

**Comment by tananaev** [comment]
@ismailyavuz, please don't comment on ancient closed threads. If you want to discuss something create a new issue.
