### ISSUE TITLE
[Doubt] Rename folder modern?

### ISSUE THREAD

**Issue by glbatistabh** [traccar/traccar#4862]
Commit `3b5c04b4ddf71223371815575fa1b652fea1d5da`, file `src/main/java/org/traccar/web/WebServer.java`, line `105` tests hardcode if the path starts with `"/modern"`.

Assuming I renamed the modern folder to `my-app` for example, what will happen? Will it give error in the code probably correct? So how should I proceed to rename the "modern" folder?

_Note: I know I will need to change the .env file in the traccar-web project and recompile it._

*Commit 3b5c04b4ddf71223371815575fa1b652fea1d5da*
https://github.com/traccar/traccar/commit/3b5c04b4ddf71223371815575fa1b652fea1d5da#diff-8699a03fbf1f6f88cf2fbeabee066402cea8fbc96e727f31cbbb945908e21abd

**Comment by tananaev** [comment]
It will continue working like before. What's not going to work is missing files handling. It is needed because of the way routing is handled in the modern app.

For example, the login path is `/modern/login`, but this folder doesn't exist. Instead it's handled by JS code. And it works if you navigate there from root, but it doesn't work when you open it directly. That's because server need to return the same `index.html` for all those folders.

Ultimately this hardcoded value is temporary. The plan is to make web app version configurable in the config file instead of being able to switch dynamically.
