### ISSUE TITLE
Error "userGroups" is null or No value specified for parameter 1 when implementing OpenID 

### ISSUE THREAD

**Issue by oliverchambers** [traccar/traccar#5262]
**Describe the bug**
I am trying to implement OpenID authentication and have gotten so far, in that the button appears on the Traccar login page, when you click on the 'login with OpenID' button it successfully redirects to our Microsoft EntraID login, I log in using my Office 365 credentials to sign in and then it successful redirects back to the Traccar server however, rather than logging me in it loads a page 

At this address:
`https://traccar.mwscouts.org/api/session/openid/callback?code=0.AQsA9fg2RNk1OECnJYSgCl4LZSS7KFib5d1CiczZZK402YOEAPk.AgABAAIAAAAmoFfGtYxvRrNriQdPKIZ-AgDs_wUA9P9GQ3c1xcFjc4A21T8DWRPMTe6ADAf0GbgMpEAy69CIGtxflnEOomk6gxFtOXqROllrfZ337Kv3-Oj7f1lqKtHfC1ZKNMvAuL6guKrv7WK9GCs_AmhDrOHUAugzUUonfuR2Dx9xWzoGkXHq9qjJsBySOfBtX7n0TpKLNzQhl_qlXGTeXNFx9WlhKA2H_bGqEVYKI4IrhhCo5S3JXqvTQ0BQbsfOEwGA2vmJaBR4HFhNAQ8tDDXn-FHAmf2YJEnsKsAKp-Eja5jaOCfBwWZZEEk_KzeznrPxesjYYJyjFHYUH3xhRqraPulzSF6E5Xepf4By4FGJhVf5NlQ80J-ITaXleFy7Vcboukgq_S0vXCtcsKaGldzpLUyLbnbe0gUaho6M4j-_pSyJCAGeo0aZ7AdEQ9nsmB8UvU1Nby30mr0V5UHxq7MkZVOTxk8qYBrUKK8ANbm-_EBO-wTx8zcOsFRCP4MnkklbPYJXmJyet9mUIBHXPT3bYvTlDjoGBfzF5NNPwj9iSfK490OT1rVwl-htj0ap2vHRDPr0ZsaKqoEZm46RqBCTEFk9OItK_nG4WmY0KrSh2LIYp5M35nbVoKFKHTGM72bEr9t08SGCGdSwb-yGvyoWLuuCO7PQ3XN4B7_VwAX14kGUKBZI1PONOwAqHqhoWwSNHcFMyUb0Ug&state=QkIMsTWxFLWJ0RY8qLUD04zc9dNcQzh5SBLBzpU49wI&session_state=f470e4b3-9828-4698-addc-e8407d3d5661#`

 With the following error:

`Cannot invoke "java.util.List.contains(Object)" because "userGroups" is null - NullPointerException (OpenIdProvider:186 < SessionResource:172 < ... < OverrideFilter:49 < ...) `

When I remove the scoping in the Traccar config file for adminGroup and allowGroup it comes up with a different error:

`No value specified for parameter 1 - SQLException (... < QueryBuilder:413 < DatabaseStorage:76 < Storage:49 < ...)`

Here is the contents of my Traccar config file

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>
<entry key='config.default'>./conf/default.xml</entry>

    <!--

    This is the main configuration file. All your configuration parameters should be placed in this file.

    Default configuration parameters are located in the "default.xml" file. You should not modify it to avoid issues
    with upgrading to a new version. Parameters in the main config file override values in the default file. Do not
    remove "config.default" parameter from this file unless you know what you are doing.

    For list of available parameters see following page: https://www.traccar.org/configuration-file/

    -->

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://localhost/traccar?zeroDateTimeBehavior=round&amp;serverTimezone=UTC&amp;allowPublicKeyRetrieval=true&amp;useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
    <entry key='database.user'>user</entry>
    <entry key='database.password'>password</entry>
    

    <!-- Open Connect SSO -->
    <entry key='openid.enable'>true</entry>
    <entry key='openid.clientId'>5828bb24-e59b-42dd-89cc-d964ae34d983</entry>
    <entry key='openid.clientSecret'>secret</entry>
    <entry key='openid.issuerUrl'>https://login.microsoftonline.com/merseyweaverscouts.org.uk/</entry>
    <entry key='openid.authUrl'>https://login.microsoftonline.com/4436f8f5-35d9-4038-a725-84a00a5e0b65/oauth2/authorize</entry>
    <entry key='openid.tokenUrl'>https://login.microsoftonline.com/4436f8f5-35d9-4038-a725-84a00a5e0b65/oauth2/token</entry>
    <entry key='openid.userInfoUrl'>https://login.microsoftonline.com/4436f8f5-35d9-4038-a725-84a00a5e0b65/openid/userinfo/</entry>
    <entry key='openid.allowGroup'>67ec7529-cd55-4199-848f-ed2c8d5ab851</entry>
    <entry key='openid.adminGroup'>068be0a7-3f2a-44a2-8eb3-4286d42a582d</entry>
    <entry key='web.url'>https://traccar.mwscouts.org</entry>

</properties>
```

**Desktop:**
 - OS: macOS Sonoma 14.2.1
 - Browser: Safari
 - Version: 17.2.1

###  Traccar ### 
Traccar Server Version - 5.12

### Web Server ###

Software: Apache/2.4.52 (Ubuntu)

### Database Server ###

Database Management System: MariaDB
Version: 10.6.16
Database Character Set: utf8mb4

**Comment by tananaev** [comment]
It looks like your provider doesn't return "groups". That's why it fails.

**Comment by oliverchambers** [comment]
Weird! 

Azure Active Directory / EntraID certain supports groups in its OIDC implementation and I am successfully using it with this Wordpress plugin https://github.com/psignoret/aad-sso-wordpress for example to login and assign different members of security groups in the directory to different Wordpress roles. It must return groups for that? I've given the app permission to read all users and groups in the directory too.

<img width="1800" alt="Screenshot 2024-01-30 at 14 49 29" src="https://github.com/traccar/traccar/assets/4114550/e1b79232-9b2e-4478-abbb-28c9a2360bdd">

**Comment by oliverchambers** [comment]
Okay I have made some progress.....

I had to add groups as an optional claim so that it is retuned in the token. I've also ensured email and upon are returned in the token

However, now I get 

`Your OpenID Groups do not permit access to Traccar. - GeneralSecurityException (OpenIdProvider:189 < SessionResource:172 < ... < OverrideFilter:49 < ...)Here are your log in details for discover Seoul app

I am a member of both the groups and the app in EntraID has access to the groups pecified in openid.allowGroup and openid.adminGroup. When I remove these entries in the Traccar config file I get this error again.

`No value specified for parameter 1 - SQLException (... < QueryBuilder:413 < DatabaseStorage:76 < Storage:49 < ...)`

Any ideas where I'm going wrong?

**Comment by tananaev** [comment]
Probably something is wrong with your `openid.allowGroup` or `openid.adminGroup`:

https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/database/OpenIdProvider.java#L188

**Comment by 4pack** [comment]
I'm having this exact same issue. I did end up getting it to work without the allowGroup or adminGroup functionality. 

You need to make sure you use the correct issuerUrl, instead of defining the URLs individually.

```
<entry key='openid.issuerUrl'>https://login.microsoftonline.com/<your-m365-tenantid>/v2.0</entry>
```


If you do put in allowGroup or adminGroup, the login will fail with the below error:

```
AADSTS650053: The application 'Traccar' asked for scope 'groups' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'
```

That UUID refers to Microsoft Graph. My guess is somehow the groups aren't being read correctly, at least on an Azure standpoint.

**Comment by gtbuchanan** [comment]
I am using ADFS without `openid.allowGroup` or `openid.adminGroup` rather than Entra ID, but I've encountered the same error:

> No value specified for parameter 1 - SQLException (... < QueryBuilder:413 < DatabaseStorage:76 < Storage:49 < ...)

I've concluded that this is because Traccar is trying to retrieve the `email` claim from the `userinfo` endpoint, but [ADFS only returns the `sub` claim](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-faq#i-m-trying-to-get-more-claims-on-the-userinfo-endpoint--but-it-s-only-returning-subject--how-can-i-get-more-claims-). Microsoft [recommends](https://learn.microsoft.com/en-us/entra/identity-platform/userinfo#consider-using-an-id-token-instead) using the `id_token` instead of the `userinfo` endpoint for performance reasons, but I don't see how this would impact Entra ID since the `email` scope is supposed to cause the `email` claim to be included in the `userinfo` response anyway. 

Unfortunately, I can't get ADFS on Windows Server 2019 to return the `email` claim in the `id_token`. It doesn't respect the `email` scope and using custom claim mappings doesn't affect the `access_token` or `id_token` at all... I can't think of a good workaround for this since Traccar doesn't have a `username` field. In other applications, I would have just used `upn` (i.e. "User Principal Name") as the username and set the email manually.
