### ISSUE TITLE
mariaDB support

### ISSUE THREAD

**Issue by vkrastanov** [traccar/traccar#675]
HI,
Normally mariadb should work just fine with the mysql-connector, however there is another java connector written especially for mariadb (and supported by mariadb comunity): https://downloads.mariadb.org/client-java/
Here's my story. I switched from mysql to mariadb couple of days ago and after running the server for few hours, the following messages are written into traccar-server.log:
2014-04-22 04:01:22  WARN: Could not send query: Last packet not finished - java.sql.SQLNonTransientConnectionException (SQLExceptionMapper.java:136)

When this happen, nothing is written into the db and only restart of the traccar-server is fixing it. I'm not sure if this is related to the connector, but if someone have any ideas I'll appreciate the help.
Thanks.

**Comment by Armagetron** [comment]
I recently switched to MariaDB. I managed to get traccar working with MariaDB. I had to modify three things in the configuration.

In traccar.cfg you need to change the database config to:
`<entry key='database.driver'>org.mariadb.jdbc.Driver</entry>`
`<entry key='database.dataSource'>org.mariadb.jdbc.MySQLDataSource</entry>`

Additionally I had to add the MariaDB jdbc to the classpath in the wrapper.cfg file:
`wrapper.java.classpath.3=/usr/share/java/mariadb-jdbc/mariadb-java-client.jar`

The default autoreconnect does not work with MariaDB because it is simple not supported. One could try the tcp timeout instead. But so far this seems to work fine.

**Comment by tananaev** [comment]
Thanks for sharing configuration parameters.
